/**
 * InsightGov Africa - Banking & Financial Services KPI Templates
 * ================================================================
 * Indicateurs de performance pour le secteur bancaire et financier
 */

import { KPITemplateDefinition } from './health';

export const bankingKPIs: KPITemplateDefinition[] = [
  // FINANCIAL INCLUSION
  {
    id: 'banking_account_penetration',
    name: 'Bank Account Penetration',
    nameFr: 'Taux de bancarisation',
    category: 'inclusion',
    calculation: '(Adults with bank account / Adult population) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 8.10',
    frequency: 'annual',
    dimensions: ['region', 'urban_rural', 'gender'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_mobile_money',
    name: 'Mobile Money Penetration',
    nameFr: 'Pénétration mobile money',
    category: 'inclusion',
    calculation: '(Mobile money accounts / Adult population) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 8.10',
    frequency: 'annual',
    dimensions: ['region', 'provider'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_branch_density',
    name: 'Branch Density',
    nameFr: 'Densité d\'agences',
    category: 'inclusion',
    calculation: 'Bank branches per 100,000 adults',
    unit: '/100,000',
    format: 'number',
    target: 15,
    sdgAlignment: 'ODD 8.10',
    frequency: 'annual',
    dimensions: ['region', 'bank_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'banking_atm_density',
    name: 'ATM Density',
    nameFr: 'Densité de DAB',
    category: 'inclusion',
    calculation: 'ATMs per 100,000 adults',
    unit: '/100,000',
    format: 'number',
    target: 40,
    sdgAlignment: 'ODD 8.10',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'banking_agent_network',
    name: 'Banking Agent Network',
    nameFr: 'Réseau d\'agents bancaires',
    category: 'inclusion',
    calculation: 'Total banking agents',
    unit: 'agents',
    format: 'number',
    target: 10000,
    sdgAlignment: 'ODD 8.10',
    frequency: 'annual',
    dimensions: ['region', 'bank'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'banking_credit_access',
    name: 'Credit Access Rate',
    nameFr: 'Accès au crédit',
    category: 'inclusion',
    calculation: '(Adults with bank credit / Adult population) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 8.10',
    frequency: 'annual',
    dimensions: ['region', 'credit_type'],
    visualization: { defaultType: 'gauge' }
  },

  // LOAN PORTFOLIO
  {
    id: 'banking_loan_portfolio',
    name: 'Total Loan Portfolio',
    nameFr: 'Encours crédits total',
    category: 'lending',
    calculation: 'Total outstanding loans',
    unit: 'USD',
    format: 'currency',
    target: 10000000000,
    frequency: 'monthly',
    dimensions: ['bank', 'loan_type', 'sector'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'banking_npl_ratio',
    name: 'Non-Performing Loan Ratio',
    nameFr: 'Taux de créances douteuses',
    category: 'lending',
    calculation: '(NPLs / Total loans) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'quarterly',
    dimensions: ['bank', 'loan_type', 'sector'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'banking_provision_coverage',
    name: 'Loan Loss Provision Coverage',
    nameFr: 'Couverture des provisions',
    category: 'lending',
    calculation: '(Provisions / NPLs) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_lending_rate',
    name: 'Average Lending Rate',
    nameFr: 'Taux moyen prêteur',
    category: 'lending',
    calculation: 'Weighted average interest rate on loans',
    unit: '%',
    format: 'percentage',
    target: 12,
    frequency: 'monthly',
    dimensions: ['loan_type', 'bank'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_credit_to_gdp',
    name: 'Credit to GDP Ratio',
    nameFr: 'Crédit au secteur privé/PIB',
    category: 'lending',
    calculation: '(Private sector credit / GDP) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 8.10',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_sme_lending',
    name: 'SME Lending Share',
    nameFr: 'Part des crédits PME',
    category: 'lending',
    calculation: '(SME loans / Total loans) × 100',
    unit: '%',
    format: 'percentage',
    target: 25,
    sdgAlignment: 'ODD 8.3',
    frequency: 'annual',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_agri_lending',
    name: 'Agricultural Lending Share',
    nameFr: 'Part des crédits agricoles',
    category: 'lending',
    calculation: '(Agricultural loans / Total loans) × 100',
    unit: '%',
    format: 'percentage',
    target: 15,
    frequency: 'annual',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },

  // DEPOSITS
  {
    id: 'banking_deposit_base',
    name: 'Total Deposit Base',
    nameFr: 'Total des dépôts',
    category: 'deposits',
    calculation: 'Total customer deposits',
    unit: 'USD',
    format: 'currency',
    target: 15000000000,
    frequency: 'monthly',
    dimensions: ['bank', 'deposit_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'banking_deposit_growth',
    name: 'Deposit Growth Rate',
    nameFr: 'Croissance des dépôts',
    category: 'deposits',
    calculation: '((Current - Previous) / Previous) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    frequency: 'annual',
    dimensions: ['bank', 'deposit_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_loan_to_deposit',
    name: 'Loan-to-Deposit Ratio',
    nameFr: 'Ratio crédits/dépôts',
    category: 'deposits',
    calculation: '(Total loans / Total deposits) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'monthly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_casa_ratio',
    name: 'CASA Ratio',
    nameFr: 'Ratio CASA',
    category: 'deposits',
    calculation: '(Current + Savings accounts / Total deposits) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    frequency: 'monthly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_deposit_rate',
    name: 'Average Deposit Rate',
    nameFr: 'Taux moyen dépôt',
    category: 'deposits',
    calculation: 'Weighted average interest rate on deposits',
    unit: '%',
    format: 'percentage',
    target: 4,
    frequency: 'monthly',
    dimensions: ['deposit_type'],
    visualization: { defaultType: 'gauge' }
  },

  // PROFITABILITY
  {
    id: 'banking_net_interest_margin',
    name: 'Net Interest Margin',
    nameFr: 'Marge nette d\'intérêts',
    category: 'profitability',
    calculation: '(Interest income - Interest expense) / Average earning assets × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_roa',
    name: 'Return on Assets',
    nameFr: 'Rentabilité des actifs',
    category: 'profitability',
    calculation: '(Net income / Total assets) × 100',
    unit: '%',
    format: 'percentage',
    target: 2,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_roe',
    name: 'Return on Equity',
    nameFr: 'Rentabilité des fonds propres',
    category: 'profitability',
    calculation: '(Net income / Shareholders equity) × 100',
    unit: '%',
    format: 'percentage',
    target: 15,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_cost_income',
    name: 'Cost-to-Income Ratio',
    nameFr: 'Ratio coût/revenu',
    category: 'profitability',
    calculation: '(Operating costs / Operating income) × 100',
    unit: '%',
    format: 'percentage',
    target: 60,
    lowerIsBetter: true,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'banking_cost_of_funds',
    name: 'Cost of Funds',
    nameFr: 'Coût des ressources',
    category: 'profitability',
    calculation: 'Interest expense / Average interest-bearing liabilities × 100',
    unit: '%',
    format: 'percentage',
    target: 3,
    lowerIsBetter: true,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // CAPITAL ADEQUACY
  {
    id: 'banking_car',
    name: 'Capital Adequacy Ratio',
    nameFr: 'Ratio de solvabilité',
    category: 'capital',
    calculation: '(Capital / Risk-weighted assets) × 100',
    unit: '%',
    format: 'percentage',
    target: 15,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_tier1_ratio',
    name: 'Tier 1 Capital Ratio',
    nameFr: 'Ratio Tier 1',
    category: 'capital',
    calculation: '(Tier 1 capital / Risk-weighted assets) × 100',
    unit: '%',
    format: 'percentage',
    target: 12,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_leverage_ratio',
    name: 'Leverage Ratio',
    nameFr: 'Ratio de levier',
    category: 'capital',
    calculation: '(Tier 1 capital / Total exposure) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },

  // LIQUIDITY
  {
    id: 'banking_liquidity_ratio',
    name: 'Liquidity Ratio',
    nameFr: 'Ratio de liquidité',
    category: 'liquidity',
    calculation: '(Liquid assets / Total deposits) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    frequency: 'monthly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_lcr',
    name: 'Liquidity Coverage Ratio',
    nameFr: 'Ratio de couverture liquidité',
    category: 'liquidity',
    calculation: '(High-quality liquid assets / Net cash outflows) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    frequency: 'monthly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_nsf_ratio',
    name: 'Net Stable Funding Ratio',
    nameFr: 'Ratio de financement stable',
    category: 'liquidity',
    calculation: '(Available stable funding / Required stable funding) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // OPERATIONAL EFFICIENCY
  {
    id: 'banking_customers_per_branch',
    name: 'Customers per Branch',
    nameFr: 'Clients par agence',
    category: 'efficiency',
    calculation: 'Total customers / Total branches',
    unit: 'customers',
    format: 'number',
    target: 5000,
    frequency: 'annual',
    dimensions: ['bank', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'banking_transactions_atm',
    name: 'ATM Transactions Share',
    nameFr: 'Part transactions DAB',
    category: 'efficiency',
    calculation: '(ATM transactions / Total transactions) × 100',
    unit: '%',
    format: 'percentage',
    target: 40,
    frequency: 'monthly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_digital_transactions',
    name: 'Digital Transactions Share',
    nameFr: 'Part transactions digitales',
    category: 'efficiency',
    calculation: '(Digital transactions / Total transactions) × 100',
    unit: '%',
    format: 'percentage',
    target: 60,
    sdgAlignment: 'ODD 8.10',
    frequency: 'monthly',
    dimensions: ['bank', 'channel'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_cost_per_transaction',
    name: 'Cost per Transaction',
    nameFr: 'Coût par transaction',
    category: 'efficiency',
    calculation: 'Total operating costs / Total transactions',
    unit: 'USD',
    format: 'currency',
    target: 0.5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['bank', 'channel'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'banking_fraud_rate',
    name: 'Fraud Rate',
    nameFr: 'Taux de fraude',
    category: 'efficiency',
    calculation: '(Fraud amount / Total transactions) × 100',
    unit: '%',
    format: 'percentage',
    target: 0.01,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['bank', 'channel'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // CUSTOMER SERVICE
  {
    id: 'banking_customer_satisfaction',
    name: 'Customer Satisfaction Score',
    nameFr: 'Score satisfaction client',
    category: 'service',
    calculation: '(Satisfied customers / Surveyed) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'quarterly',
    dimensions: ['bank', 'service_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_nps',
    name: 'Net Promoter Score',
    nameFr: 'Score Net Promoter',
    category: 'service',
    calculation: '% Promoters - % Detractors',
    unit: 'score',
    format: 'number',
    target: 40,
    frequency: 'quarterly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'banking_complaint_resolution',
    name: 'Complaint Resolution Rate',
    nameFr: 'Taux de résolution plaintes',
    category: 'service',
    calculation: '(Resolved complaints / Total complaints) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'monthly',
    dimensions: ['bank'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'banking_account_opening_time',
    name: 'Account Opening Time',
    nameFr: 'Délai ouverture compte',
    category: 'service',
    calculation: 'Average minutes to open account',
    unit: 'minutes',
    format: 'number',
    target: 15,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['bank', 'account_type'],
    visualization: { defaultType: 'kpi' }
  },
];

export default bankingKPIs;
