/**
 * InsightGov Africa - Construction & Public Works KPI Templates
 * ===============================================================
 * Indicateurs de performance pour le secteur du BTP et construction
 */

import { KPITemplateDefinition } from './health';

export const constructionKPIs: KPITemplateDefinition[] = [
  // PROJECT MANAGEMENT
  {
    id: 'construction_schedule_performance',
    name: 'Schedule Performance Index',
    nameFr: 'Indice de performance planning',
    category: 'project',
    calculation: '(Earned value / Planned value) × 100',
    unit: 'index',
    format: 'number',
    target: 100,
    frequency: 'weekly',
    dimensions: ['project', 'phase'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'construction_cost_performance',
    name: 'Cost Performance Index',
    nameFr: 'Indice de performance coût',
    category: 'project',
    calculation: '(Earned value / Actual cost) × 100',
    unit: 'index',
    format: 'number',
    target: 100,
    frequency: 'weekly',
    dimensions: ['project', 'phase'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'construction_on_time',
    name: 'On-Time Completion Rate',
    nameFr: 'Taux d\'achèvement à temps',
    category: 'project',
    calculation: '(Projects completed on time / Total projects) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    sdgAlignment: 'ODD 9.1',
    frequency: 'monthly',
    dimensions: ['project_type', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'construction_budget_variance',
    name: 'Budget Variance',
    nameFr: 'Écart budgétaire',
    category: 'project',
    calculation: '((Actual - Budget) / Budget) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['project', 'category'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_change_orders',
    name: 'Change Order Rate',
    nameFr: 'Taux d\'avenants',
    category: 'project',
    calculation: '(Change order value / Original contract) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['project', 'cause'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_claim_rate',
    name: 'Claim Rate',
    nameFr: 'Taux de réclamations',
    category: 'project',
    calculation: '(Claims value / Total project value) × 100',
    unit: '%',
    format: 'percentage',
    target: 2,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // PRODUCTIVITY
  {
    id: 'construction_labor_productivity',
    name: 'Labor Productivity',
    nameFr: 'Productivité main d\'œuvre',
    category: 'productivity',
    calculation: 'Work completed / Labor hours',
    unit: 'units/hour',
    format: 'number',
    target: 100,
    frequency: 'daily',
    dimensions: ['project', 'trade', 'activity'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'construction_equipment_utilization',
    name: 'Equipment Utilization',
    nameFr: 'Utilisation équipements',
    category: 'productivity',
    calculation: '(Operating hours / Available hours) × 100',
    unit: '%',
    format: 'percentage',
    target: 75,
    frequency: 'daily',
    dimensions: ['project', 'equipment_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'construction_progress_rate',
    name: 'Construction Progress Rate',
    nameFr: 'Taux d\'avancement',
    category: 'productivity',
    calculation: '(Completed work / Total work) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    frequency: 'weekly',
    dimensions: ['project', 'phase'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'construction_productivity_index',
    name: 'Productivity Index',
    nameFr: 'Indice de productivité',
    category: 'productivity',
    calculation: '(Actual output / Standard output) × 100',
    unit: 'index',
    format: 'number',
    target: 100,
    frequency: 'weekly',
    dimensions: ['project', 'trade'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'construction_cycle_time',
    name: 'Construction Cycle Time',
    nameFr: 'Temps de cycle construction',
    category: 'productivity',
    calculation: 'Days to complete typical floor/unit',
    unit: 'days',
    format: 'number',
    target: 10,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['project_type'],
    visualization: { defaultType: 'kpi' }
  },

  // QUALITY
  {
    id: 'construction_rework_rate',
    name: 'Rework Rate',
    nameFr: 'Taux de reprise',
    category: 'quality',
    calculation: '(Rework cost / Total project cost) × 100',
    unit: '%',
    format: 'percentage',
    target: 2,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['project', 'trade'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_defect_rate',
    name: 'Defect Rate',
    nameFr: 'Taux de défauts',
    category: 'quality',
    calculation: '(Defects found / Inspections) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['project', 'element'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_first_time_quality',
    name: 'First-Time Quality Rate',
    nameFr: 'Qualité au premier passage',
    category: 'quality',
    calculation: '(Passed inspections / Total inspections) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    frequency: 'weekly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'construction_warranty_claims',
    name: 'Warranty Claim Rate',
    nameFr: 'Taux de réclamation garantie',
    category: 'quality',
    calculation: '(Warranty claims / Completed projects) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: ['project_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_quality_audits',
    name: 'Quality Audit Score',
    nameFr: 'Score audit qualité',
    category: 'quality',
    calculation: 'Average score from quality audits',
    unit: 'score',
    format: 'number',
    target: 90,
    frequency: 'quarterly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // SAFETY
  {
    id: 'construction_ltir',
    name: 'Lost Time Injury Rate',
    nameFr: 'Taux d\'accidents avec arrêt',
    category: 'safety',
    calculation: '(LTI × 1,000,000) / Hours worked',
    unit: '/M hours',
    format: 'number',
    target: 1,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['project', 'trade'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'construction_trir',
    name: 'Total Recordable Injury Rate',
    nameFr: 'Taux total d\'accidents',
    category: 'safety',
    calculation: '(TRI × 200,000) / Hours worked',
    unit: '/200k hours',
    format: 'number',
    target: 2,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['project'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'construction_fatalities',
    name: 'Fatality Rate',
    nameFr: 'Taux de mortalité',
    category: 'safety',
    calculation: 'Fatalities per 100,000 workers',
    unit: '/100,000',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'annual',
    dimensions: ['project_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'construction_safety_audits',
    name: 'Safety Audit Score',
    nameFr: 'Score audit sécurité',
    category: 'safety',
    calculation: 'Average safety audit score',
    unit: 'score',
    format: 'number',
    target: 90,
    sdgAlignment: 'ODD 8.8',
    frequency: 'quarterly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'construction_near_misses',
    name: 'Near Miss Reporting Rate',
    nameFr: 'Rapports presque-accidents',
    category: 'safety',
    calculation: 'Near misses reported per 100 workers',
    unit: '/100 workers',
    format: 'number',
    target: 10,
    frequency: 'monthly',
    dimensions: ['project'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'construction_safety_training',
    name: 'Safety Training Compliance',
    nameFr: 'Conformité formation sécurité',
    category: 'safety',
    calculation: '(Workers trained / Workers required) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // FINANCIAL
  {
    id: 'construction_gross_margin',
    name: 'Project Gross Margin',
    nameFr: 'Marge brute projet',
    category: 'financial',
    calculation: '(Revenue - Direct costs) / Revenue × 100',
    unit: '%',
    format: 'percentage',
    target: 15,
    frequency: 'monthly',
    dimensions: ['project', 'type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'construction_overhead_ratio',
    name: 'Overhead Ratio',
    nameFr: 'Ratio frais généraux',
    category: 'financial',
    calculation: '(Overhead costs / Revenue) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: [],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_cash_flow',
    name: 'Cash Flow Performance',
    nameFr: 'Performance trésorerie',
    category: 'financial',
    calculation: '(Collections - Payments) / Contract value × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    frequency: 'monthly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'construction_retention',
    name: 'Retention Held',
    nameFr: 'Rétention de garantie',
    category: 'financial',
    calculation: 'Total retention held as % of contract',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_payment_terms',
    name: 'Payment Collection Days',
    nameFr: 'Délai encaissement',
    category: 'financial',
    calculation: 'Average days to collect payment',
    unit: 'days',
    format: 'number',
    target: 45,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['client_type'],
    visualization: { defaultType: 'kpi' }
  },

  // RESOURCES
  {
    id: 'construction_material_waste',
    name: 'Material Waste Rate',
    nameFr: 'Taux de perte matériaux',
    category: 'resources',
    calculation: '(Wasted material / Total material) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 12.2',
    frequency: 'monthly',
    dimensions: ['project', 'material_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_labor_turnover',
    name: 'Labor Turnover Rate',
    nameFr: 'Taux de rotation personnel',
    category: 'resources',
    calculation: '(Departures / Average workforce) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['trade'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'construction_subcontractor_performance',
    name: 'Subcontractor Performance Score',
    nameFr: 'Score performance sous-traitants',
    category: 'resources',
    calculation: 'Average score from subcontractor evaluations',
    unit: 'score',
    format: 'number',
    target: 80,
    frequency: 'monthly',
    dimensions: ['subcontractor', 'trade'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'construction_material_availability',
    name: 'Material Availability Rate',
    nameFr: 'Disponibilité matériaux',
    category: 'resources',
    calculation: '(Materials on time / Materials needed) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'weekly',
    dimensions: ['project', 'material_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // INFRASTRUCTURE DELIVERY
  {
    id: 'construction_infra_delivered',
    name: 'Infrastructure Delivered',
    nameFr: 'Infrastructure livrée',
    category: 'delivery',
    calculation: 'Total km or units of infrastructure completed',
    unit: 'km',
    format: 'number',
    target: 500,
    sdgAlignment: 'ODD 9.1',
    frequency: 'annual',
    dimensions: ['infrastructure_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'construction_housing_units',
    name: 'Housing Units Delivered',
    nameFr: 'Logements livrés',
    category: 'delivery',
    calculation: 'Total housing units completed',
    unit: 'units',
    format: 'number',
    target: 10000,
    sdgAlignment: 'ODD 11.1',
    frequency: 'annual',
    dimensions: ['region', 'housing_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'construction_public_buildings',
    name: 'Public Buildings Completed',
    nameFr: 'Bâtiments publics achevés',
    category: 'delivery',
    calculation: 'Total public buildings completed',
    unit: 'buildings',
    format: 'number',
    target: 100,
    sdgAlignment: 'ODD 11.1',
    frequency: 'annual',
    dimensions: ['building_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'construction_water_infra',
    name: 'Water Infrastructure Delivered',
    nameFr: 'Infrastructure eau livrée',
    category: 'delivery',
    calculation: 'Total water infrastructure completed',
    unit: 'km',
    format: 'number',
    target: 1000,
    sdgAlignment: 'ODD 6.1',
    frequency: 'annual',
    dimensions: ['infrastructure_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },

  // ENVIRONMENT
  {
    id: 'construction_dust_compliance',
    name: 'Dust Control Compliance',
    nameFr: 'Conformité contrôle poussière',
    category: 'environment',
    calculation: '(Compliant days / Total days) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 11.6',
    frequency: 'monthly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'construction_noise_compliance',
    name: 'Noise Level Compliance',
    nameFr: 'Conformité niveau sonore',
    category: 'environment',
    calculation: '(Compliant days / Total days) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    sdgAlignment: 'ODD 11.6',
    frequency: 'monthly',
    dimensions: ['project'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'construction_waste_recycling',
    name: 'Construction Waste Recycling',
    nameFr: 'Recyclage déchets chantier',
    category: 'environment',
    calculation: '(Recycled waste / Total waste) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    sdgAlignment: 'ODD 12.5',
    frequency: 'monthly',
    dimensions: ['project', 'waste_type'],
    visualization: { defaultType: 'gauge' }
  },
];

export default constructionKPIs;
