/**
 * InsightGov Africa - Energy (Oil, Gas, Electricity) KPI Templates
 * =================================================================
 * Indicateurs de performance pour le secteur énergétique
 */

import { KPITemplateDefinition } from './health';

export const energyKPIs: KPITemplateDefinition[] = [
  // ELECTRICITY GENERATION
  {
    id: 'energy_generation_total',
    name: 'Total Electricity Generation',
    nameFr: 'Production électrique totale',
    category: 'generation',
    calculation: 'Total GWh generated',
    unit: 'GWh',
    format: 'number',
    target: 10000,
    sdgAlignment: 'ODD 7.1',
    frequency: 'monthly',
    dimensions: ['plant_type', 'fuel_source', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_capacity_installed',
    name: 'Installed Capacity',
    nameFr: 'Capacité installée',
    category: 'generation',
    calculation: 'Total MW installed',
    unit: 'MW',
    format: 'number',
    target: 3000,
    sdgAlignment: 'ODD 7.1',
    frequency: 'annual',
    dimensions: ['plant_type', 'fuel_source'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_capacity_factor',
    name: 'Capacity Factor',
    nameFr: 'Facteur de capacité',
    category: 'generation',
    calculation: '(Actual generation / Maximum possible) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    frequency: 'monthly',
    dimensions: ['plant', 'type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'energy_plant_availability',
    name: 'Plant Availability Factor',
    nameFr: 'Disponibilité des centrales',
    category: 'generation',
    calculation: '(Available hours / Total hours) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    frequency: 'monthly',
    dimensions: ['plant', 'type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'energy_renewable_share',
    name: 'Renewable Energy Share',
    nameFr: 'Part des énergies renouvelables',
    category: 'generation',
    calculation: '(Renewable generation / Total generation) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 7.2',
    frequency: 'monthly',
    dimensions: ['source_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'energy_solar_capacity',
    name: 'Solar Capacity',
    nameFr: 'Capacité solaire',
    category: 'generation',
    calculation: 'Total MW of solar capacity',
    unit: 'MW',
    format: 'number',
    target: 500,
    sdgAlignment: 'ODD 7.2',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_wind_capacity',
    name: 'Wind Capacity',
    nameFr: 'Capacité éolienne',
    category: 'generation',
    calculation: 'Total MW of wind capacity',
    unit: 'MW',
    format: 'number',
    target: 300,
    sdgAlignment: 'ODD 7.2',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_hydro_capacity',
    name: 'Hydro Capacity',
    nameFr: 'Capacité hydroélectrique',
    category: 'generation',
    calculation: 'Total MW of hydro capacity',
    unit: 'MW',
    format: 'number',
    target: 1000,
    sdgAlignment: 'ODD 7.2',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },

  // TRANSMISSION & DISTRIBUTION
  {
    id: 'energy_grid_losses',
    name: 'Transmission & Distribution Losses',
    nameFr: 'Pertes réseau',
    category: 'distribution',
    calculation: '(Energy lost / Energy supplied) × 100',
    unit: '%',
    format: 'percentage',
    target: 12,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 7.3',
    frequency: 'monthly',
    dimensions: ['region', 'voltage_level'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'energy_saifi',
    name: 'SAIFI (Interruption Frequency)',
    nameFr: 'Fréquence d\'interruption',
    category: 'distribution',
    calculation: 'Average interruptions per customer',
    unit: 'interruptions',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 7.1',
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_saidi',
    name: 'SAIDI (Interruption Duration)',
    nameFr: 'Durée d\'interruption',
    category: 'distribution',
    calculation: 'Average outage hours per customer',
    unit: 'hours',
    format: 'number',
    target: 20,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 7.1',
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_grid_reliability',
    name: 'Grid Reliability Index',
    nameFr: 'Indice de fiabilité réseau',
    category: 'distribution',
    calculation: 'Percentage of time power is available',
    unit: '%',
    format: 'percentage',
    target: 99,
    sdgAlignment: 'ODD 7.1',
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'energy_line_length',
    name: 'Total Grid Length',
    nameFr: 'Longueur totale réseau',
    category: 'distribution',
    calculation: 'Total km of transmission lines',
    unit: 'km',
    format: 'number',
    target: 10000,
    frequency: 'annual',
    dimensions: ['voltage_level', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_substation_capacity',
    name: 'Substation Capacity',
    nameFr: 'Capacité sous-stations',
    category: 'distribution',
    calculation: 'Total MVA of substation capacity',
    unit: 'MVA',
    format: 'number',
    target: 5000,
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },

  // ACCESS & ELECTRIFICATION
  {
    id: 'energy_electrification_rate',
    name: 'Electrification Rate',
    nameFr: 'Taux d\'électrification',
    category: 'access',
    calculation: '(Population with electricity / Total population) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 7.1',
    frequency: 'annual',
    dimensions: ['region', 'urban_rural'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'energy_rural_electrification',
    name: 'Rural Electrification Rate',
    nameFr: 'Électrification rurale',
    category: 'access',
    calculation: '(Rural population with electricity / Rural population) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 7.1',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'energy_new_connections',
    name: 'New Connections per Year',
    nameFr: 'Nouveaux raccordements',
    category: 'access',
    calculation: 'Total new grid connections',
    unit: 'connections',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 7.1',
    frequency: 'annual',
    dimensions: ['region', 'customer_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_time_connection',
    name: 'Time to Connect',
    nameFr: 'Délai de raccordement',
    category: 'access',
    calculation: 'Average days from application to connection',
    unit: 'days',
    format: 'number',
    target: 30,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['connection_type'],
    visualization: { defaultType: 'kpi' }
  },

  // CONSUMPTION
  {
    id: 'energy_per_capita',
    name: 'Per Capita Consumption',
    nameFr: 'Consommation par habitant',
    category: 'consumption',
    calculation: 'Total consumption / Population',
    unit: 'kWh/person',
    format: 'number',
    target: 500,
    sdgAlignment: 'ODD 7.1',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_peak_demand',
    name: 'Peak Demand',
    nameFr: 'Demande de pointe',
    category: 'consumption',
    calculation: 'Maximum MW demand',
    unit: 'MW',
    format: 'number',
    target: 2000,
    frequency: 'monthly',
    dimensions: ['region', 'season'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_load_factor',
    name: 'Load Factor',
    nameFr: 'Facteur de charge',
    category: 'consumption',
    calculation: '(Average load / Peak load) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'energy_demand_growth',
    name: 'Electricity Demand Growth',
    nameFr: 'Croissance demande électrique',
    category: 'consumption',
    calculation: '((Current - Previous) / Previous) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    frequency: 'annual',
    dimensions: ['region', 'customer_type'],
    visualization: { defaultType: 'gauge' }
  },

  // FINANCIAL
  {
    id: 'energy_tariff_cost',
    name: 'Average Tariff',
    nameFr: 'Tarif moyen',
    category: 'financial',
    calculation: 'Average price per kWh',
    unit: 'USD/kWh',
    format: 'currency',
    target: 0.15,
    frequency: 'annual',
    dimensions: ['customer_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_bill_collection',
    name: 'Bill Collection Rate',
    nameFr: 'Taux de recouvrement',
    category: 'financial',
    calculation: '(Amount collected / Amount billed) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'monthly',
    dimensions: ['region', 'customer_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'energy_atc_loss',
    name: 'ATC&C Losses',
    nameFr: 'Pertes ATC&C',
    category: 'financial',
    calculation: 'Technical + Commercial losses as % of generation',
    unit: '%',
    format: 'percentage',
    target: 15,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'energy_cost_recovery',
    name: 'Cost Recovery Ratio',
    nameFr: 'Ratio couverture coûts',
    category: 'financial',
    calculation: '(Revenue / Total cost) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'energy_subsidy_per_kwh',
    name: 'Subsidy per kWh',
    nameFr: 'Subvention par kWh',
    category: 'financial',
    calculation: 'Total subsidy / Total kWh sold',
    unit: 'USD/kWh',
    format: 'currency',
    target: 0.02,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'kpi' }
  },

  // OIL & GAS
  {
    id: 'energy_oil_production',
    name: 'Crude Oil Production',
    nameFr: 'Production pétrole brut',
    category: 'oil_gas',
    calculation: 'Total barrels per day',
    unit: 'bbl/day',
    format: 'number',
    target: 100000,
    frequency: 'monthly',
    dimensions: ['field', 'operator'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_gas_production',
    name: 'Natural Gas Production',
    nameFr: 'Production gaz naturel',
    category: 'oil_gas',
    calculation: 'Total cubic meters per day',
    unit: 'm³/day',
    format: 'number',
    target: 10000000,
    frequency: 'monthly',
    dimensions: ['field', 'operator'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_refining_capacity',
    name: 'Refining Capacity',
    nameFr: 'Capacité de raffinage',
    category: 'oil_gas',
    calculation: 'Total barrels per day refined',
    unit: 'bbl/day',
    format: 'number',
    target: 50000,
    frequency: 'annual',
    dimensions: ['refinery'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_gas_flaring',
    name: 'Gas Flaring Rate',
    nameFr: 'Taux de torchage',
    category: 'oil_gas',
    calculation: '(Flared gas / Total gas produced) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.2',
    frequency: 'monthly',
    dimensions: ['field', 'operator'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'energy_fuel_imports',
    name: 'Fuel Import Dependency',
    nameFr: 'Dépendance importations carburants',
    category: 'oil_gas',
    calculation: '(Fuel imports / Total consumption) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 7.1',
    frequency: 'annual',
    dimensions: ['fuel_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'energy_strategic_reserve',
    name: 'Strategic Petroleum Reserve',
    nameFr: 'Réserve stratégique pétrole',
    category: 'oil_gas',
    calculation: 'Days of consumption in reserve',
    unit: 'days',
    format: 'number',
    target: 90,
    frequency: 'monthly',
    dimensions: ['fuel_type'],
    visualization: { defaultType: 'kpi' }
  },

  // ENVIRONMENTAL
  {
    id: 'energy_co2_intensity',
    name: 'CO2 Intensity of Generation',
    nameFr: 'Intensité CO2 de production',
    category: 'environment',
    calculation: 'CO2 emissions per GWh',
    unit: 'tons CO2/GWh',
    format: 'number',
    target: 400,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.2',
    frequency: 'annual',
    dimensions: ['fuel_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_efficiency',
    name: 'Energy Intensity',
    nameFr: 'Intensité énergétique',
    category: 'environment',
    calculation: 'Energy used per unit GDP',
    unit: 'MJ/USD',
    format: 'number',
    target: 3,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 7.3',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'energy_clean_cooking',
    name: 'Clean Cooking Access',
    nameFr: 'Accès cuisson propre',
    category: 'environment',
    calculation: '(Population with clean cooking / Total population) × 100',
    unit: '%',
    format: 'percentage',
    target: 60,
    sdgAlignment: 'ODD 7.1',
    frequency: 'annual',
    dimensions: ['region', 'urban_rural'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
];

export default energyKPIs;
