/**
 * InsightGov Africa - Environment KPI Templates
 * ==============================================
 * Indicateurs de performance pour le secteur de l'environnement
 */

import { KPITemplateDefinition } from './health';

export const environmentKPIs: KPITemplateDefinition[] = [
  // AIR QUALITY
  {
    id: 'environment_pm25',
    name: 'PM2.5 Concentration',
    nameFr: 'Concentration PM2.5',
    category: 'air',
    calculation: 'Average PM2.5 concentration',
    unit: 'μg/m³',
    format: 'number',
    target: 25,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 11.6',
    frequency: 'daily',
    dimensions: ['city', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'environment_pm10',
    name: 'PM10 Concentration',
    nameFr: 'Concentration PM10',
    category: 'air',
    calculation: 'Average PM10 concentration',
    unit: 'μg/m³',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 11.6',
    frequency: 'daily',
    dimensions: ['city', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'environment_aqi_good_days',
    name: 'Good Air Quality Days',
    nameFr: 'Jours bonne qualité air',
    category: 'air',
    calculation: '(Days with AQI < 100 / Total days) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 11.6',
    frequency: 'annual',
    dimensions: ['city'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_co2_emissions',
    name: 'CO2 Emissions per Capita',
    nameFr: 'Émissions CO2 par habitant',
    category: 'air',
    calculation: 'Total CO2 emissions / Population',
    unit: 'tons/person',
    format: 'number',
    target: 2,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.2',
    frequency: 'annual',
    dimensions: ['sector'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_ghg_emissions',
    name: 'GHG Emissions',
    nameFr: 'Émissions GES',
    category: 'air',
    calculation: 'Total greenhouse gas emissions',
    unit: 'Mt CO2e',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.2',
    frequency: 'annual',
    dimensions: ['sector', 'gas_type'],
    visualization: { defaultType: 'kpi' }
  },

  // WATER QUALITY
  {
    id: 'environment_water_quality_index',
    name: 'Water Quality Index',
    nameFr: 'Indice qualité eau',
    category: 'water',
    calculation: 'Composite water quality score',
    unit: 'index',
    format: 'number',
    target: 80,
    sdgAlignment: 'ODD 6.3',
    frequency: 'monthly',
    dimensions: ['water_body', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_river_quality',
    name: 'Rivers Meeting Standards',
    nameFr: 'Rivières conformes',
    category: 'water',
    calculation: '(Compliant rivers / Monitored rivers) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    sdgAlignment: 'ODD 6.3',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_wastewater_treatment',
    name: 'Wastewater Treatment Rate',
    nameFr: 'Taux traitement eaux usées',
    category: 'water',
    calculation: '(Treated wastewater / Generated wastewater) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 6.3',
    frequency: 'annual',
    dimensions: ['region', 'treatment_level'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'environment_industrial_effluent',
    name: 'Industrial Effluent Compliance',
    nameFr: 'Conformité effluents industriels',
    category: 'water',
    calculation: '(Compliant facilities / Total facilities) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    sdgAlignment: 'ODD 6.3',
    frequency: 'annual',
    dimensions: ['industry_type', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_groundwater_level',
    name: 'Groundwater Level Change',
    nameFr: 'Variation nappe phréatique',
    category: 'water',
    calculation: 'Average change in groundwater level',
    unit: 'meters',
    format: 'number',
    target: 0,
    sdgAlignment: 'ODD 6.6',
    frequency: 'annual',
    dimensions: ['aquifer', 'region'],
    visualization: { defaultType: 'kpi' }
  },

  // BIODIVERSITY
  {
    id: 'environment_protected_areas',
    name: 'Protected Area Coverage',
    nameFr: 'Aires protégées',
    category: 'biodiversity',
    calculation: '(Protected area / Total land) × 100',
    unit: '%',
    format: 'percentage',
    target: 17,
    sdgAlignment: 'ODD 15.1',
    frequency: 'annual',
    dimensions: ['protection_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_forest_cover',
    name: 'Forest Coverage',
    nameFr: 'Couverture forestière',
    category: 'biodiversity',
    calculation: '(Forest area / Total land) × 100',
    unit: '%',
    format: 'percentage',
    target: 25,
    sdgAlignment: 'ODD 15.1',
    frequency: 'annual',
    dimensions: ['forest_type', 'region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'environment_deforestation',
    name: 'Deforestation Rate',
    nameFr: 'Taux de déforestation',
    category: 'biodiversity',
    calculation: '(Forest loss / Forest area) × 100',
    unit: '%',
    format: 'percentage',
    target: 0.5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 15.2',
    frequency: 'annual',
    dimensions: ['region', 'cause'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'environment_species_threatened',
    name: 'Threatened Species',
    nameFr: 'Espèces menacées',
    category: 'biodiversity',
    calculation: 'Number of threatened species',
    unit: 'species',
    format: 'number',
    target: 100,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 15.5',
    frequency: 'annual',
    dimensions: ['species_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_marine_protected',
    name: 'Marine Protected Areas',
    nameFr: 'Aires marines protégées',
    category: 'biodiversity',
    calculation: '(Marine protected area / Territorial waters) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    sdgAlignment: 'ODD 14.5',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'environment_reforestation',
    name: 'Reforestation Area',
    nameFr: 'Surface reboisée',
    category: 'biodiversity',
    calculation: 'Total hectares reforested',
    unit: 'hectares',
    format: 'number',
    target: 50000,
    sdgAlignment: 'ODD 15.2',
    frequency: 'annual',
    dimensions: ['region', 'project_type'],
    visualization: { defaultType: 'kpi' }
  },

  // WASTE MANAGEMENT
  {
    id: 'environment_waste_collection',
    name: 'Waste Collection Coverage',
    nameFr: 'Couverture collecte déchets',
    category: 'waste',
    calculation: '(Population with collection / Total population) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 11.6',
    frequency: 'annual',
    dimensions: ['region', 'urban_rural'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_recycling_rate',
    name: 'Recycling Rate',
    nameFr: 'Taux de recyclage',
    category: 'waste',
    calculation: '(Recycled waste / Total waste) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 12.5',
    frequency: 'annual',
    dimensions: ['waste_type', 'region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'environment_landfill_rate',
    name: 'Landfill Disposal Rate',
    nameFr: 'Taux mise en décharge',
    category: 'waste',
    calculation: '(Landfilled waste / Total waste) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 12.4',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'environment_waste_per_capita',
    name: 'Waste per Capita',
    nameFr: 'Déchets par habitant',
    category: 'waste',
    calculation: 'Total waste generated / Population',
    unit: 'kg/person/year',
    format: 'number',
    target: 200,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 12.5',
    frequency: 'annual',
    dimensions: ['region', 'urban_rural'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_hazardous_waste',
    name: 'Hazardous Waste Managed',
    nameFr: 'Déchets dangereux traités',
    category: 'waste',
    calculation: '(Managed hazardous waste / Generated) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    sdgAlignment: 'ODD 12.4',
    frequency: 'annual',
    dimensions: ['waste_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_illegal_dumping',
    name: 'Illegal Dumping Sites',
    nameFr: 'Sites de décharge illégaux',
    category: 'waste',
    calculation: 'Number of illegal dumping sites',
    unit: 'sites',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 11.6',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },

  // CLIMATE CHANGE
  {
    id: 'environment_renewable_energy',
    name: 'Renewable Energy Share',
    nameFr: 'Part énergies renouvelables',
    category: 'climate',
    calculation: '(Renewable energy / Total energy) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 7.2',
    frequency: 'annual',
    dimensions: ['source_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'environment_carbon_intensity',
    name: 'Carbon Intensity of GDP',
    nameFr: 'Intensité carbone PIB',
    category: 'climate',
    calculation: 'CO2 emissions / GDP',
    unit: 'kg CO2/USD',
    format: 'number',
    target: 0.2,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.2',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_climate_vulnerability',
    name: 'Climate Vulnerability Index',
    nameFr: 'Indice vulnérabilité climatique',
    category: 'climate',
    calculation: 'Composite vulnerability score',
    unit: 'index',
    format: 'number',
    target: 30,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.1',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'environment_disaster_events',
    name: 'Climate-Related Disasters',
    nameFr: 'Catastrophes climatiques',
    category: 'climate',
    calculation: 'Number of climate-related disaster events',
    unit: 'events',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.1',
    frequency: 'annual',
    dimensions: ['disaster_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_adaptation_funding',
    name: 'Climate Adaptation Funding',
    nameFr: 'Financement adaptation climatique',
    category: 'climate',
    calculation: 'Total climate adaptation funding received',
    unit: 'USD',
    format: 'currency',
    target: 100000000,
    sdgAlignment: 'ODD 13.1',
    frequency: 'annual',
    dimensions: ['source', 'project_type'],
    visualization: { defaultType: 'kpi' }
  },

  // LAND DEGRADATION
  {
    id: 'environment_land_degradation',
    name: 'Land Degradation Rate',
    nameFr: 'Taux de dégradation des terres',
    category: 'land',
    calculation: '(Degraded land / Total land) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 15.3',
    frequency: 'annual',
    dimensions: ['region', 'degradation_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'environment_desertification',
    name: 'Desertification Rate',
    nameFr: 'Taux de désertification',
    category: 'land',
    calculation: 'Area affected by desertification',
    unit: 'km²',
    format: 'number',
    target: 1000,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 15.3',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_soil_erosion',
    name: 'Soil Erosion Rate',
    nameFr: 'Taux érosion sols',
    category: 'land',
    calculation: 'Average soil loss per hectare',
    unit: 'tons/ha/year',
    format: 'number',
    target: 10,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 15.3',
    frequency: 'annual',
    dimensions: ['region', 'land_use'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_land_restoration',
    name: 'Land Restoration Area',
    nameFr: 'Surface terres restaurées',
    category: 'land',
    calculation: 'Total hectares of land restored',
    unit: 'hectares',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 15.3',
    frequency: 'annual',
    dimensions: ['region', 'restoration_type'],
    visualization: { defaultType: 'kpi' }
  },

  // POLLUTION CONTROL
  {
    id: 'environment_noise_pollution',
    name: 'Noise Pollution Level',
    nameFr: 'Niveau pollution sonore',
    category: 'pollution',
    calculation: 'Average noise level in urban areas',
    unit: 'dB',
    format: 'number',
    target: 55,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 11.6',
    frequency: 'annual',
    dimensions: ['city', 'zone_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_chemical_safety',
    name: 'Chemical Safety Compliance',
    nameFr: 'Conformité sécurité chimique',
    category: 'pollution',
    calculation: '(Compliant facilities / Total facilities) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 12.4',
    frequency: 'annual',
    dimensions: ['industry_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_oil_spills',
    name: 'Oil Spill Incidents',
    nameFr: 'Incidents déversements pétrole',
    category: 'pollution',
    calculation: 'Number of oil spill incidents',
    unit: 'incidents',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 14.1',
    frequency: 'annual',
    dimensions: ['location', 'cause'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'environment_plastic_waste',
    name: 'Plastic Waste Reduction',
    nameFr: 'Réduction déchets plastiques',
    category: 'pollution',
    calculation: 'Percentage reduction in plastic waste',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 14.1',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },

  // ENVIRONMENTAL GOVERNANCE
  {
    id: 'environment_eia_compliance',
    name: 'EIA Compliance Rate',
    nameFr: 'Conformité EIE',
    category: 'governance',
    calculation: '(Projects with EIA / Required projects) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 16.6',
    frequency: 'annual',
    dimensions: ['project_type', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'environment_enforcement',
    name: 'Environmental Enforcement',
    nameFr: 'Application lois environnement',
    category: 'governance',
    calculation: '(Violations penalized / Violations detected) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 16.6',
    frequency: 'annual',
    dimensions: ['violation_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'environment_green_budget',
    name: 'Green Budget Share',
    nameFr: 'Part budget vert',
    category: 'governance',
    calculation: '(Environmental spending / Total budget) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    sdgAlignment: 'ODD 13.2',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },
];

export default environmentKPIs;
