/**
 * InsightGov Africa - Fisheries & Aquaculture KPI Templates
 * ============================================================
 * Indicateurs de performance pour le secteur de la pêche et de l'aquaculture
 */

import { KPITemplateDefinition } from './health';

export const fisheriesKPIs: KPITemplateDefinition[] = [
  // FISHING PRODUCTION
  {
    id: 'fisheries_catch_volume',
    name: 'Total Catch Volume',
    nameFr: 'Volume total des captures',
    category: 'production',
    calculation: 'Total tonnes of fish caught',
    unit: 'tonnes',
    format: 'number',
    target: 500000,
    sdgAlignment: 'ODD 14.4',
    frequency: 'monthly',
    dimensions: ['fishery_type', 'species', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_catch_per_unit',
    name: 'Catch per Unit Effort (CPUE)',
    nameFr: 'Capture par unité effort',
    category: 'production',
    calculation: 'Catch (kg) / Fishing effort (hours)',
    unit: 'kg/hour',
    format: 'number',
    target: 50,
    sdgAlignment: 'ODD 14.4',
    frequency: 'monthly',
    dimensions: ['fishery_type', 'vessel_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_fleet_size',
    name: 'Active Fishing Fleet',
    nameFr: 'Flotte de pêche active',
    category: 'production',
    calculation: 'Total active fishing vessels',
    unit: 'vessels',
    format: 'number',
    target: 5000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['vessel_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_fisher_count',
    name: 'Total Fishers',
    nameFr: 'Nombre de pêcheurs',
    category: 'production',
    calculation: 'Total people employed in fishing',
    unit: 'fishers',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['fishery_type', 'region', 'gender'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_value',
    name: 'Fisheries Value',
    nameFr: 'Valeur des pêches',
    category: 'production',
    calculation: 'Total value of catch at landing',
    unit: 'USD',
    format: 'currency',
    target: 500000000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'monthly',
    dimensions: ['species', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_export_value',
    name: 'Fisheries Export Value',
    nameFr: 'Valeur exportations pêche',
    category: 'production',
    calculation: 'Total value of fish exports',
    unit: 'USD',
    format: 'currency',
    target: 200000000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'monthly',
    dimensions: ['species', 'destination'],
    visualization: { defaultType: 'kpi' }
  },

  // AQUACULTURE
  {
    id: 'fisheries_aquaculture_production',
    name: 'Aquaculture Production',
    nameFr: 'Production aquacole',
    category: 'aquaculture',
    calculation: 'Total tonnes from aquaculture',
    unit: 'tonnes',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'monthly',
    dimensions: ['species', 'system_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_aquaculture_farms',
    name: 'Aquaculture Farms',
    nameFr: 'Exploitations aquacoles',
    category: 'aquaculture',
    calculation: 'Total registered aquaculture farms',
    unit: 'farms',
    format: 'number',
    target: 2000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['farm_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_aquaculture_productivity',
    name: 'Aquaculture Yield',
    nameFr: 'Rendement aquacole',
    category: 'aquaculture',
    calculation: 'Production per hectare per year',
    unit: 'tonnes/ha/year',
    format: 'number',
    target: 5,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['species', 'system_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_feed_conversion',
    name: 'Feed Conversion Ratio',
    nameFr: 'Taux de conversion alimentaire',
    category: 'aquaculture',
    calculation: 'Feed input / Weight gain',
    unit: 'ratio',
    format: 'ratio',
    target: 1.5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['species'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_hatchery_production',
    name: 'Hatchery Production',
    nameFr: 'Production éclosérie',
    category: 'aquaculture',
    calculation: 'Total fingerlings/juveniles produced',
    unit: 'millions',
    format: 'number',
    target: 50,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['species', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_aquaculture_share',
    name: 'Aquaculture Share of Production',
    nameFr: 'Part aquaculture production',
    category: 'aquaculture',
    calculation: '(Aquaculture / Total fish production) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },

  // SUSTAINABILITY
  {
    id: 'fisheries_overfished',
    name: 'Overfished Stocks',
    nameFr: 'Stocks surexploités',
    category: 'sustainability',
    calculation: '(Overfished stocks / Total stocks) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 14.4',
    frequency: 'annual',
    dimensions: ['species', 'zone'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'fisheries_msy_compliance',
    name: 'MSY Compliance Rate',
    nameFr: 'Conformité MSY',
    category: 'sustainability',
    calculation: '(Stocks fished sustainably / Total stocks) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 14.4',
    frequency: 'annual',
    dimensions: ['species'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'fisheries_bycatch_rate',
    name: 'Bycatch Rate',
    nameFr: 'Taux de captures accessoires',
    category: 'sustainability',
    calculation: '(Bycatch / Total catch) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 14.6',
    frequency: 'monthly',
    dimensions: ['fishery_type', 'gear_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'fisheries_discard_rate',
    name: 'Discard Rate',
    nameFr: 'Taux de rejets',
    category: 'sustainability',
    calculation: '(Discarded catch / Total catch) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 14.6',
    frequency: 'monthly',
    dimensions: ['fishery_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'fisheries_mpa_coverage',
    name: 'Marine Protected Areas',
    nameFr: 'Aires marines protégées',
    category: 'sustainability',
    calculation: '(MPA area / Territorial waters) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 14.5',
    frequency: 'annual',
    dimensions: ['zone'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'fisheries_illegal_fishing',
    name: 'IUU Fishing Incidents',
    nameFr: 'Incidents pêche INN',
    category: 'sustainability',
    calculation: 'Number of illegal fishing incidents',
    unit: 'incidents',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 14.4',
    frequency: 'monthly',
    dimensions: ['zone', 'violation_type'],
    visualization: { defaultType: 'kpi' }
  },

  // FISHING COMMUNITIES
  {
    id: 'fisheries_fisher_income',
    name: 'Average Fisher Income',
    nameFr: 'Revenu moyen pêcheurs',
    category: 'livelihoods',
    calculation: 'Average annual income per fisher',
    unit: 'USD/year',
    format: 'currency',
    target: 3000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['fishery_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_fisher_organizations',
    name: 'Fisher Organizations',
    nameFr: 'Organisations de pêcheurs',
    category: 'livelihoods',
    calculation: 'Total registered fisher cooperatives',
    unit: 'organizations',
    format: 'number',
    target: 500,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_processing_jobs',
    name: 'Fish Processing Employment',
    nameFr: 'Emploi transformation poisson',
    category: 'livelihoods',
    calculation: 'Total jobs in fish processing',
    unit: 'jobs',
    format: 'number',
    target: 50000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['processing_type', 'region', 'gender'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_fisher_women',
    name: 'Women in Fisheries',
    nameFr: 'Femmes dans la pêche',
    category: 'livelihoods',
    calculation: '(Women in fisheries / Total fishers) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 5.1',
    frequency: 'annual',
    dimensions: ['role_type'],
    visualization: { defaultType: 'gauge' }
  },

  // FOOD SECURITY
  {
    id: 'fisheries_fish_consumption',
    name: 'Per Capita Fish Consumption',
    nameFr: 'Consommation poisson par habitant',
    category: 'food',
    calculation: 'Total fish consumption / Population',
    unit: 'kg/person/year',
    format: 'number',
    target: 20,
    sdgAlignment: 'ODD 2.1',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_protein_share',
    name: 'Fish Protein Share',
    nameFr: 'Part protéines poisson',
    category: 'food',
    calculation: '(Fish protein / Total animal protein) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 2.1',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'fisheries_processing_capacity',
    name: 'Processing Capacity Utilization',
    nameFr: 'Utilisation capacité transformation',
    category: 'food',
    calculation: '(Actual processed / Capacity) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    frequency: 'monthly',
    dimensions: ['processing_type', 'region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'fisheries_post_harvest_loss',
    name: 'Post-Harvest Loss Rate',
    nameFr: 'Taux de perte post-capture',
    category: 'food',
    calculation: '(Lost fish / Total catch) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 12.3',
    frequency: 'monthly',
    dimensions: ['loss_point', 'species'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // GOVERNANCE
  {
    id: 'fisheries_licensed_vessels',
    name: 'Licensed Vessel Rate',
    nameFr: 'Taux navires licenciés',
    category: 'governance',
    calculation: '(Licensed vessels / Total vessels) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 14.4',
    frequency: 'annual',
    dimensions: ['vessel_type', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'fisheries_monitoring',
    name: 'Vessel Monitoring Coverage',
    nameFr: 'Couverture suivi navires',
    category: 'governance',
    calculation: '(Vessels with VMS / Total vessels) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 14.4',
    frequency: 'annual',
    dimensions: ['vessel_category'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'fisheries_observer_coverage',
    name: 'Observer Coverage',
    nameFr: 'Couverture observateurs',
    category: 'governance',
    calculation: '(Observed trips / Total trips) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    sdgAlignment: 'ODD 14.4',
    frequency: 'annual',
    dimensions: ['fishery_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'fisheries_enforcement',
    name: 'Enforcement Actions',
    nameFr: 'Actions de contrôle',
    category: 'governance',
    calculation: 'Total enforcement actions taken',
    unit: 'actions',
    format: 'number',
    target: 500,
    sdgAlignment: 'ODD 14.4',
    frequency: 'monthly',
    dimensions: ['violation_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_subsidies',
    name: 'Harmful Subsidies Reduction',
    nameFr: 'Réduction subventions nuisibles',
    category: 'governance',
    calculation: 'Reduction in harmful fishing subsidies',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 14.6',
    frequency: 'annual',
    dimensions: ['subsidy_type'],
    visualization: { defaultType: 'gauge' }
  },

  // INFRASTRUCTURE
  {
    id: 'fisheries_landing_sites',
    name: 'Landing Sites',
    nameFr: 'Sites de débarquement',
    category: 'infrastructure',
    calculation: 'Total operational landing sites',
    unit: 'sites',
    format: 'number',
    target: 200,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['region', 'site_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_cold_storage',
    name: 'Cold Storage Capacity',
    nameFr: 'Capacité froid',
    category: 'infrastructure',
    calculation: 'Total cold storage capacity',
    unit: 'tonnes',
    format: 'number',
    target: 50000,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_ports',
    name: 'Fishing Ports',
    nameFr: 'Ports de pêche',
    category: 'infrastructure',
    calculation: 'Total fishing ports/harbors',
    unit: 'ports',
    format: 'number',
    target: 50,
    sdgAlignment: 'ODD 14.7',
    frequency: 'annual',
    dimensions: ['region', 'port_size'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'fisheries_research_stations',
    name: 'Research Stations',
    nameFr: 'Stations de recherche',
    category: 'infrastructure',
    calculation: 'Total fisheries research stations',
    unit: 'stations',
    format: 'number',
    target: 20,
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
];

export default fisheriesKPIs;
