/**
 * InsightGov Africa - Human Resources KPI Templates
 * ===================================================
 * Indicateurs de performance pour les ressources humaines
 */

import { KPITemplateDefinition } from './health';

export const hrKPIs: KPITemplateDefinition[] = [
  // RECRUITMENT
  {
    id: 'hr_time_to_hire',
    name: 'Time to Hire',
    nameFr: 'Délai de recrutement',
    category: 'recruitment',
    calculation: 'Average days from job posting to offer acceptance',
    unit: 'days',
    format: 'number',
    target: 30,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['department', 'position_level'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'hr_cost_per_hire',
    name: 'Cost per Hire',
    nameFr: 'Coût par recrutement',
    category: 'recruitment',
    calculation: 'Total recruitment costs / Number of hires',
    unit: 'USD',
    format: 'currency',
    target: 3000,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['department', 'source'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'hr_vacancy_rate',
    name: 'Vacancy Rate',
    nameFr: 'Taux de vacance',
    category: 'recruitment',
    calculation: '(Vacant positions / Total positions) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['department', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'hr_offer_acceptance',
    name: 'Offer Acceptance Rate',
    nameFr: 'Taux acceptation offres',
    category: 'recruitment',
    calculation: '(Offers accepted / Offers extended) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'monthly',
    dimensions: ['department', 'position_level'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_applications_per_position',
    name: 'Applications per Position',
    nameFr: 'Candidatures par poste',
    category: 'recruitment',
    calculation: 'Total applications / Open positions',
    unit: 'applications',
    format: 'number',
    target: 20,
    frequency: 'monthly',
    dimensions: ['department'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'hr_quality_of_hire',
    name: 'Quality of Hire Score',
    nameFr: 'Score qualité recrutement',
    category: 'recruitment',
    calculation: 'Composite score based on performance and retention',
    unit: 'score',
    format: 'number',
    target: 80,
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // TURNOVER
  {
    id: 'hr_turnover_rate',
    name: 'Employee Turnover Rate',
    nameFr: 'Taux de rotation',
    category: 'turnover',
    calculation: '(Departures / Average workforce) × 100',
    unit: '%',
    format: 'percentage',
    target: 15,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.5',
    frequency: 'monthly',
    dimensions: ['department', 'reason', 'tenure'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'hr_voluntary_turnover',
    name: 'Voluntary Turnover Rate',
    nameFr: 'Taux de départ volontaire',
    category: 'turnover',
    calculation: '(Voluntary departures / Workforce) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['department', 'tenure'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'hr_retention_rate',
    name: 'Employee Retention Rate',
    nameFr: 'Taux de rétention',
    category: 'turnover',
    calculation: '(Employees retained / Total employees) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    sdgAlignment: 'ODD 8.5',
    frequency: 'annual',
    dimensions: ['department', 'tenure'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_early_turnover',
    name: 'Early Turnover Rate',
    nameFr: 'Taux de départ anticipé',
    category: 'turnover',
    calculation: '(Departures <1 year / New hires) × 100',
    unit: '%',
    format: 'percentage',
    target: 15,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // ENGAGEMENT
  {
    id: 'hr_engagement_score',
    name: 'Employee Engagement Score',
    nameFr: 'Score engagement employés',
    category: 'engagement',
    calculation: 'Average score from engagement surveys',
    unit: 'score',
    format: 'number',
    target: 75,
    sdgAlignment: 'ODD 8.5',
    frequency: 'quarterly',
    dimensions: ['department', 'tenure', 'level'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_satisfaction_score',
    name: 'Job Satisfaction Score',
    nameFr: 'Score satisfaction travail',
    category: 'engagement',
    calculation: 'Average score from satisfaction surveys',
    unit: 'score',
    format: 'number',
    target: 80,
    frequency: 'quarterly',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_nps',
    name: 'Employee Net Promoter Score',
    nameFr: 'eNPS',
    category: 'engagement',
    calculation: '% Promoters - % Detractors',
    unit: 'score',
    format: 'number',
    target: 30,
    frequency: 'quarterly',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_absenteeism',
    name: 'Absenteeism Rate',
    nameFr: 'Taux d\'absentéisme',
    category: 'engagement',
    calculation: '(Absent days / Scheduled days) × 100',
    unit: '%',
    format: 'percentage',
    target: 3,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['department', 'absence_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // PERFORMANCE
  {
    id: 'hr_performance_distribution',
    name: 'High Performer Share',
    nameFr: 'Part hauts performeurs',
    category: 'performance',
    calculation: '(High performers / Total employees) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    frequency: 'annual',
    dimensions: ['department', 'level'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_goal_achievement',
    name: 'Goal Achievement Rate',
    nameFr: 'Taux atteinte objectifs',
    category: 'performance',
    calculation: '(Goals achieved / Goals set) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_promotion_rate',
    name: 'Internal Promotion Rate',
    nameFr: 'Taux promotion interne',
    category: 'performance',
    calculation: '(Internal promotions / Total positions filled) × 100',
    unit: '%',
    format: 'percentage',
    target: 40,
    sdgAlignment: 'ODD 8.5',
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_succession_readiness',
    name: 'Succession Readiness',
    nameFr: 'Préparation succession',
    category: 'performance',
    calculation: '(Positions with successors / Critical positions) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // TRAINING
  {
    id: 'hr_training_hours',
    name: 'Training Hours per Employee',
    nameFr: 'Heures formation par employé',
    category: 'training',
    calculation: 'Total training hours / Total employees',
    unit: 'hours',
    format: 'number',
    target: 40,
    sdgAlignment: 'ODD 4.4',
    frequency: 'annual',
    dimensions: ['department', 'training_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'hr_training_spend',
    name: 'Training Spend per Employee',
    nameFr: 'Dépense formation par employé',
    category: 'training',
    calculation: 'Total training budget / Total employees',
    unit: 'USD',
    format: 'currency',
    target: 1000,
    sdgAlignment: 'ODD 4.4',
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'hr_training_completion',
    name: 'Training Completion Rate',
    nameFr: 'Taux achèvement formation',
    category: 'training',
    calculation: '(Completed trainings / Assigned trainings) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    sdgAlignment: 'ODD 4.4',
    frequency: 'quarterly',
    dimensions: ['department', 'training_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_skills_gap',
    name: 'Skills Gap Index',
    nameFr: 'Indice écart compétences',
    category: 'training',
    calculation: 'Average gap between current and required skills',
    unit: 'index',
    format: 'number',
    target: 10,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: ['department', 'skill_category'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // COMPENSATION
  {
    id: 'hr_competitiveness',
    name: 'Salary Competitiveness Ratio',
    nameFr: 'Ratio compétitivité salaire',
    category: 'compensation',
    calculation: 'Average salary / Market average × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    frequency: 'annual',
    dimensions: ['position_level', 'department'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_compensation_ratio',
    name: 'Compensation Ratio',
    nameFr: 'Ratio compensation',
    category: 'compensation',
    calculation: '(Total compensation / Revenue) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    frequency: 'monthly',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_benefits_participation',
    name: 'Benefits Participation Rate',
    nameFr: 'Participation avantages sociaux',
    category: 'compensation',
    calculation: '(Employees enrolled / Employees eligible) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'annual',
    dimensions: ['benefit_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_pay_equity',
    name: 'Pay Equity Ratio',
    nameFr: 'Ratio équité salariale',
    category: 'compensation',
    calculation: 'Female avg salary / Male avg salary × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 5.1',
    frequency: 'annual',
    dimensions: ['position_level', 'department'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // DIVERSITY
  {
    id: 'hr_gender_diversity',
    name: 'Gender Diversity',
    nameFr: 'Diversité genre',
    category: 'diversity',
    calculation: '(Underrepresented gender / Total) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 5.1',
    frequency: 'annual',
    dimensions: ['department', 'level'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_women_leadership',
    name: 'Women in Leadership',
    nameFr: 'Femmes en leadership',
    category: 'diversity',
    calculation: '(Women in leadership / Leadership positions) × 100',
    unit: '%',
    format: 'percentage',
    target: 40,
    sdgAlignment: 'ODD 5.5',
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_age_diversity',
    name: 'Age Diversity Index',
    nameFr: 'Indice diversité âge',
    category: 'diversity',
    calculation: 'Simpson diversity index for age groups',
    unit: 'index',
    format: 'number',
    target: 0.7,
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_disability_inclusion',
    name: 'Disability Employment Rate',
    nameFr: 'Taux emploi handicapés',
    category: 'diversity',
    calculation: '(Employees with disabilities / Total employees) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    sdgAlignment: 'ODD 8.5',
    frequency: 'annual',
    dimensions: ['department'],
    visualization: { defaultType: 'gauge' }
  },

  // HR EFFICIENCY
  {
    id: 'hr_ratio',
    name: 'HR to Employee Ratio',
    nameFr: 'Ratio RH par employé',
    category: 'efficiency',
    calculation: 'Total employees / HR staff',
    unit: ':1',
    format: 'ratio',
    target: 100,
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'hr_admin_cost',
    name: 'HR Admin Cost per Employee',
    nameFr: 'Coût admin RH par employé',
    category: 'efficiency',
    calculation: 'Total HR costs / Total employees',
    unit: 'USD',
    format: 'currency',
    target: 500,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'hr_self_service',
    name: 'HR Self-Service Adoption',
    nameFr: 'Adoption self-service RH',
    category: 'efficiency',
    calculation: '(Self-service transactions / Total transactions) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    frequency: 'monthly',
    dimensions: ['transaction_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_ticket_resolution',
    name: 'HR Ticket Resolution Time',
    nameFr: 'Délai résolution tickets RH',
    category: 'efficiency',
    calculation: 'Average hours to resolve HR tickets',
    unit: 'hours',
    format: 'number',
    target: 24,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['ticket_type'],
    visualization: { defaultType: 'kpi' }
  },

  // COMPLIANCE
  {
    id: 'hr_policy_compliance',
    name: 'Policy Compliance Rate',
    nameFr: 'Taux conformité politiques',
    category: 'compliance',
    calculation: '(Compliant areas / Total areas audited) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'annual',
    dimensions: ['policy_area'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'hr_grievance_resolution',
    name: 'Grievance Resolution Rate',
    nameFr: 'Taux résolution griefs',
    category: 'compliance',
    calculation: '(Resolved grievances / Total grievances) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['grievance_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'hr_contract_compliance',
    name: 'Contract Compliance Rate',
    nameFr: 'Conformité contrats',
    category: 'compliance',
    calculation: '(Compliant contracts / Total contracts) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 8.8',
    frequency: 'annual',
    dimensions: ['contract_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
];

export default hrKPIs;
