/**
 * InsightGov Africa - Justice & Legal System KPI Templates
 * ==========================================================
 * Indicateurs de performance pour le secteur de la justice
 */

import { KPITemplateDefinition } from './health';

export const justiceKPIs: KPITemplateDefinition[] = [
  // CASE MANAGEMENT
  {
    id: 'justice_case_backlog',
    name: 'Case Backlog',
    nameFr: 'Arriéré d\'affaires',
    category: 'case_management',
    calculation: 'Total pending cases',
    unit: 'cases',
    format: 'number',
    target: 5000,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['court', 'case_type', 'jurisdiction'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_case_clearance',
    name: 'Case Clearance Rate',
    nameFr: 'Taux de clearance',
    category: 'case_management',
    calculation: '(Cases resolved / Cases filed) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['court', 'case_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'justice_disposition_time',
    name: 'Average Case Duration',
    nameFr: 'Durée moyenne des affaires',
    category: 'case_management',
    calculation: 'Average days from filing to disposition',
    unit: 'days',
    format: 'number',
    target: 180,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.3',
    frequency: 'quarterly',
    dimensions: ['court', 'case_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_cases_filed',
    name: 'Cases Filed',
    nameFr: 'Affaires déposées',
    category: 'case_management',
    calculation: 'Total new cases filed',
    unit: 'cases',
    format: 'number',
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['court', 'case_type', 'jurisdiction'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_cases_resolved',
    name: 'Cases Resolved',
    nameFr: 'Affaires résolues',
    category: 'case_management',
    calculation: 'Total cases disposed',
    unit: 'cases',
    format: 'number',
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['court', 'case_type', 'disposition_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_trial_rate',
    name: 'Trial Rate',
    nameFr: 'Taux de procès',
    category: 'case_management',
    calculation: '(Cases going to trial / Total cases) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    frequency: 'annual',
    dimensions: ['court', 'case_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'justice_settlement_rate',
    name: 'Settlement Rate',
    nameFr: 'Taux de règlement',
    category: 'case_management',
    calculation: '(Settled cases / Total cases) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['case_type'],
    visualization: { defaultType: 'gauge' }
  },

  // ACCESS TO JUSTICE
  {
    id: 'justice_legal_aid',
    name: 'Legal Aid Recipients',
    nameFr: 'Bénéficiaires aide juridique',
    category: 'access',
    calculation: 'Total people receiving legal aid',
    unit: 'persons',
    format: 'number',
    target: 50000,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region', 'case_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_legal_aid_coverage',
    name: 'Legal Aid Coverage',
    nameFr: 'Couverture aide juridique',
    category: 'access',
    calculation: '(Legal aid recipients / Eligible population) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'justice_court_density',
    name: 'Courts per Capita',
    nameFr: 'Tribunaux par habitant',
    category: 'access',
    calculation: 'Courts per 100,000 population',
    unit: '/100,000',
    format: 'number',
    target: 2,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region', 'court_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_judge_ratio',
    name: 'Judges per Capita',
    nameFr: 'Juges par habitant',
    category: 'access',
    calculation: 'Judges per 100,000 population',
    unit: '/100,000',
    format: 'number',
    target: 5,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_pro_bono',
    name: 'Pro Bono Hours',
    nameFr: 'Heures pro bono',
    category: 'access',
    calculation: 'Total pro bono legal hours provided',
    unit: 'hours',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_mobile_courts',
    name: 'Mobile Court Sessions',
    nameFr: 'Sessions itinérantes',
    category: 'access',
    calculation: 'Total mobile court sessions held',
    unit: 'sessions',
    format: 'number',
    target: 200,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },

  // DETENTION & CORRECTIONS
  {
    id: 'justice_prison_population',
    name: 'Prison Population',
    nameFr: 'Population carcérale',
    category: 'detention',
    calculation: 'Total inmates in custody',
    unit: 'inmates',
    format: 'number',
    target: 10000,
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['facility', 'status', 'gender'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_occupancy_rate',
    name: 'Prison Occupancy Rate',
    nameFr: 'Taux d\'occupation prisons',
    category: 'detention',
    calculation: '(Actual inmates / Capacity) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['facility', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'justice_pretrial_detainees',
    name: 'Pretrial Detainee Share',
    nameFr: 'Part détenus préventifs',
    category: 'detention',
    calculation: '(Pretrial detainees / Total inmates) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['facility', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'justice_pretrial_duration',
    name: 'Average Pretrial Duration',
    nameFr: 'Durée moyenne détention préventive',
    category: 'detention',
    calculation: 'Average days in pretrial detention',
    unit: 'days',
    format: 'number',
    target: 90,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.3',
    frequency: 'quarterly',
    dimensions: ['facility'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_recidivism',
    name: 'Recidivism Rate',
    nameFr: 'Taux de récidive',
    category: 'detention',
    calculation: '(Re-offenders / Released prisoners) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['offense_type', 'time_period'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'justice_juvenile_detainees',
    name: 'Juvenile Detainees',
    nameFr: 'Mineurs détenus',
    category: 'detention',
    calculation: 'Total minors in detention',
    unit: 'minors',
    format: 'number',
    target: 100,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['facility', 'age_group'],
    visualization: { defaultType: 'kpi' }
  },

  // HUMAN RIGHTS
  {
    id: 'justice_rights_violations',
    name: 'Human Rights Violations Reported',
    nameFr: 'Violations droits humain rapportées',
    category: 'rights',
    calculation: 'Total reported human rights violations',
    unit: 'cases',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'annual',
    dimensions: ['type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_prison_deaths',
    name: 'Prison Death Rate',
    nameFr: 'Taux de mortalité carcérale',
    category: 'rights',
    calculation: '(Deaths / Average inmate population) × 1,000',
    unit: '/1,000',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'annual',
    dimensions: ['facility', 'cause'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_torture_cases',
    name: 'Torture/Ill-treatment Cases',
    nameFr: 'Cas de torture/mauvais traitements',
    category: 'rights',
    calculation: 'Reported cases of torture or ill-treatment',
    unit: 'cases',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'annual',
    dimensions: ['facility_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_fair_trial',
    name: 'Fair Trial Compliance',
    nameFr: 'Conformité procès équitable',
    category: 'rights',
    calculation: '(Compliant trials / Audited trials) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['court'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // JUDICIAL INTEGRITY
  {
    id: 'justice_corruption_cases',
    name: 'Corruption Cases in Judiciary',
    nameFr: 'Cas de corruption judiciaire',
    category: 'integrity',
    calculation: 'Total corruption cases involving judiciary',
    unit: 'cases',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.5',
    frequency: 'annual',
    dimensions: ['type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_ethics_violations',
    name: 'Judicial Ethics Violations',
    nameFr: 'Violations éthique judiciaire',
    category: 'integrity',
    calculation: 'Total ethics violations by judicial officers',
    unit: 'cases',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: ['violation_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_disciplinary_actions',
    name: 'Disciplinary Actions',
    nameFr: 'Mesures disciplinaires',
    category: 'integrity',
    calculation: 'Total disciplinary actions against judicial officers',
    unit: 'actions',
    format: 'number',
    frequency: 'annual',
    dimensions: ['action_type'],
    visualization: { defaultType: 'kpi' }
  },

  // EFFICIENCY
  {
    id: 'justice_judge_productivity',
    name: 'Judge Productivity',
    nameFr: 'Productivité des juges',
    category: 'efficiency',
    calculation: 'Cases resolved per judge per year',
    unit: 'cases/judge',
    format: 'number',
    target: 200,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['court', 'case_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_court_hours',
    name: 'Court Sitting Hours',
    nameFr: 'Heures d\'audience',
    category: 'efficiency',
    calculation: 'Average court sitting hours per day',
    unit: 'hours/day',
    format: 'number',
    target: 6,
    frequency: 'monthly',
    dimensions: ['court'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_case_management_tech',
    name: 'Digital Case Management',
    nameFr: 'Gestion numérique des dossiers',
    category: 'efficiency',
    calculation: '(Cases managed digitally / Total cases) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 16.6',
    frequency: 'annual',
    dimensions: ['court'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'justice_e_filing',
    name: 'E-Filing Rate',
    nameFr: 'Taux de dépôt électronique',
    category: 'efficiency',
    calculation: '(Cases filed electronically / Total filed) × 100',
    unit: '%',
    format: 'percentage',
    target: 60,
    sdgAlignment: 'ODD 16.6',
    frequency: 'monthly',
    dimensions: ['court', 'case_type'],
    visualization: { defaultType: 'gauge' }
  },

  // PUBLIC TRUST
  {
    id: 'justice_trust_index',
    name: 'Public Trust in Judiciary',
    nameFr: 'Confiance dans la justice',
    category: 'trust',
    calculation: 'Composite score from public surveys',
    unit: 'index',
    format: 'number',
    target: 70,
    sdgAlignment: 'ODD 16.6',
    frequency: 'annual',
    dimensions: ['demographic'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'justice_perceived_independence',
    name: 'Perceived Judicial Independence',
    nameFr: 'Indépendance perçue',
    category: 'trust',
    calculation: 'Score from independence surveys',
    unit: 'index',
    format: 'number',
    target: 75,
    sdgAlignment: 'ODD 16.6',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'justice_perceived_corruption',
    name: 'Perceived Corruption in Judiciary',
    nameFr: 'Corruption perçue',
    category: 'trust',
    calculation: 'Score from corruption perception surveys',
    unit: 'index',
    format: 'number',
    target: 30,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.5',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // LEGAL PROFESSION
  {
    id: 'justice_lawyers_ratio',
    name: 'Lawyers per Capita',
    nameFr: 'Avocats par habitant',
    category: 'profession',
    calculation: 'Lawyers per 100,000 population',
    unit: '/100,000',
    format: 'number',
    target: 20,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_bar_members',
    name: 'Bar Association Members',
    nameFr: 'Membres du barreau',
    category: 'profession',
    calculation: 'Total registered lawyers',
    unit: 'lawyers',
    format: 'number',
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region', 'specialization'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'justice_disciplinary_bar',
    name: 'Bar Disciplinary Actions',
    nameFr: 'Actions disciplinaires barreau',
    category: 'profession',
    calculation: 'Total lawyers sanctioned',
    unit: 'lawyers',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: ['violation_type'],
    visualization: { defaultType: 'kpi' }
  },
];

export default justiceKPIs;
