/**
 * InsightGov Africa - Logistics & Supply Chain KPI Templates
 * ============================================================
 * Indicateurs de performance pour la logistique et la chaîne d'approvisionnement
 */

import { KPITemplateDefinition } from './health';

export const logisticsKPIs: KPITemplateDefinition[] = [
  // WAREHOUSE MANAGEMENT
  {
    id: 'logistics_inventory_accuracy',
    name: 'Inventory Accuracy Rate',
    nameFr: 'Taux de précision des stocks',
    category: 'warehouse',
    calculation: '(Accurate inventory items / Total items counted) × 100',
    unit: '%',
    format: 'percentage',
    target: 99,
    frequency: 'monthly',
    dimensions: ['warehouse', 'product_category'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_inventory_turnover',
    name: 'Inventory Turnover Ratio',
    nameFr: 'Ratio de rotation des stocks',
    category: 'warehouse',
    calculation: 'Cost of goods sold / Average inventory',
    unit: 'ratio',
    format: 'ratio',
    target: 8,
    frequency: 'monthly',
    dimensions: ['warehouse', 'product_category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'logistics_storage_utilization',
    name: 'Warehouse Space Utilization',
    nameFr: 'Taux d\'occupation des entrepôts',
    category: 'warehouse',
    calculation: '(Used space / Total available space) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'weekly',
    dimensions: ['warehouse', 'zone_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'logistics_picking_accuracy',
    name: 'Order Picking Accuracy',
    nameFr: 'Précision des prélèvements',
    category: 'warehouse',
    calculation: '(Correct picks / Total picks) × 100',
    unit: '%',
    format: 'percentage',
    target: 99.5,
    frequency: 'daily',
    dimensions: ['warehouse', 'picker', 'shift'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_stockout_rate',
    name: 'Stock-out Rate',
    nameFr: 'Taux de rupture de stock',
    category: 'warehouse',
    calculation: '(Stock-out incidents / Total order lines) × 100',
    unit: '%',
    format: 'percentage',
    target: 2,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['warehouse', 'product_category'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'logistics_carrying_cost',
    name: 'Inventory Carrying Cost',
    nameFr: 'Coût de possession des stocks',
    category: 'warehouse',
    calculation: '(Total carrying costs / Average inventory value) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['warehouse', 'cost_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'logistics_dock_utilization',
    name: 'Dock Door Utilization',
    nameFr: 'Utilisation des quais',
    category: 'warehouse',
    calculation: '(Dock hours used / Total dock hours available) × 100',
    unit: '%',
    format: 'percentage',
    target: 75,
    frequency: 'daily',
    dimensions: ['warehouse', 'shift'],
    visualization: { defaultType: 'gauge' }
  },

  // ORDER FULFILLMENT
  {
    id: 'logistics_order_accuracy',
    name: 'Order Accuracy Rate',
    nameFr: 'Taux de précision des commandes',
    category: 'fulfillment',
    calculation: '(Perfect orders / Total orders) × 100',
    unit: '%',
    format: 'percentage',
    target: 98,
    frequency: 'daily',
    dimensions: ['channel', 'product_category', 'warehouse'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_order_cycle_time',
    name: 'Order Cycle Time',
    nameFr: 'Délai de traitement des commandes',
    category: 'fulfillment',
    calculation: 'Average (Delivery date - Order date)',
    unit: 'hours',
    format: 'number',
    target: 24,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['channel', 'region', 'priority'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'logistics_fill_rate',
    name: 'Order Fill Rate',
    nameFr: 'Taux de satisfaction des commandes',
    category: 'fulfillment',
    calculation: '(Units shipped / Units ordered) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'daily',
    dimensions: ['channel', 'product_category'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_perfect_order',
    name: 'Perfect Order Rate',
    nameFr: 'Taux de commandes parfaites',
    category: 'fulfillment',
    calculation: '(Perfect orders / Total orders) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'weekly',
    dimensions: ['channel', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_on_time_shipment',
    name: 'On-Time Shipment Rate',
    nameFr: 'Taux d\'expédition à temps',
    category: 'fulfillment',
    calculation: '(On-time shipments / Total shipments) × 100',
    unit: '%',
    format: 'percentage',
    target: 98,
    frequency: 'daily',
    dimensions: ['warehouse', 'carrier', 'priority'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // TRANSPORTATION & DELIVERY
  {
    id: 'logistics_on_time_delivery',
    name: 'On-Time Delivery Rate',
    nameFr: 'Taux de livraison à temps',
    category: 'transportation',
    calculation: '(On-time deliveries / Total deliveries) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 9.1',
    frequency: 'daily',
    dimensions: ['carrier', 'region', 'service_level'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_transit_time',
    name: 'Average Transit Time',
    nameFr: 'Temps de transit moyen',
    category: 'transportation',
    calculation: 'Average (Delivery date - Ship date)',
    unit: 'days',
    format: 'number',
    target: 3,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['route', 'carrier', 'mode'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'logistics_cost_per_unit',
    name: 'Transportation Cost per Unit',
    nameFr: 'Coût de transport par unité',
    category: 'transportation',
    calculation: 'Total transportation cost / Units shipped',
    unit: 'USD/unit',
    format: 'currency',
    target: 2,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['mode', 'route', 'product_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'logistics_fleet_utilization',
    name: 'Fleet Utilization Rate',
    nameFr: 'Taux d\'utilisation de la flotte',
    category: 'transportation',
    calculation: '(Actual load / Maximum capacity) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'weekly',
    dimensions: ['vehicle_type', 'route'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'logistics_empty_miles',
    name: 'Empty Miles Percentage',
    nameFr: 'Pourcentage de km à vide',
    category: 'transportation',
    calculation: '(Empty miles / Total miles) × 100',
    unit: '%',
    format: 'percentage',
    target: 15,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['route', 'vehicle_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'logistics_delivery_damage',
    name: 'Delivery Damage Rate',
    nameFr: 'Taux d\'avarie à la livraison',
    category: 'transportation',
    calculation: '(Damaged deliveries / Total deliveries) × 100',
    unit: '%',
    format: 'percentage',
    target: 1,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['carrier', 'product_category'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'logistics_fuel_efficiency',
    name: 'Fuel Efficiency',
    nameFr: 'Efficacité énergétique',
    category: 'transportation',
    calculation: 'Total fuel consumed / Total distance × 100',
    unit: 'L/100km',
    format: 'number',
    target: 25,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 7.3',
    frequency: 'monthly',
    dimensions: ['vehicle_type', 'route_type'],
    visualization: { defaultType: 'kpi' }
  },

  // PROCUREMENT & SUPPLY
  {
    id: 'logistics_supplier_on_time',
    name: 'Supplier On-Time Delivery',
    nameFr: 'Livraison à temps des fournisseurs',
    category: 'procurement',
    calculation: '(On-time supplier deliveries / Total supplier deliveries) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'monthly',
    dimensions: ['supplier', 'category', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_supplier_quality',
    name: 'Supplier Quality Rate',
    nameFr: 'Taux de qualité fournisseurs',
    category: 'procurement',
    calculation: '(Accepted deliveries / Total deliveries) × 100',
    unit: '%',
    format: 'percentage',
    target: 98,
    frequency: 'monthly',
    dimensions: ['supplier', 'category'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_procurement_cycle',
    name: 'Procurement Cycle Time',
    nameFr: 'Délai d\'approvisionnement',
    category: 'procurement',
    calculation: 'Average (Receipt date - Requisition date)',
    unit: 'days',
    format: 'number',
    target: 14,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['category', 'supplier_type'],
    visualization: { defaultType: 'kpi' }
  },

  // SUPPLY CHAIN PERFORMANCE
  {
    id: 'logistics_cash_to_cash',
    name: 'Cash-to-Cash Cycle Time',
    nameFr: 'Cycle de trésorerie',
    category: 'supply_chain',
    calculation: 'Inventory days + Receivables days - Payables days',
    unit: 'days',
    format: 'number',
    target: 45,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['business_unit'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'logistics_supply_chain_cost',
    name: 'Supply Chain Cost Ratio',
    nameFr: 'Ratio de coût logistique',
    category: 'supply_chain',
    calculation: '(Total SC costs / Revenue) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    frequency: 'quarterly',
    dimensions: ['cost_category'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'logistics_days_inventory',
    name: 'Days of Inventory Outstanding',
    nameFr: 'Jours de stock',
    category: 'supply_chain',
    calculation: '(Average inventory / Cost of goods sold) × 365',
    unit: 'days',
    format: 'number',
    target: 30,
    frequency: 'monthly',
    dimensions: ['product_category', 'warehouse'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'logistics_forecast_accuracy',
    name: 'Demand Forecast Accuracy',
    nameFr: 'Précision des prévisions de demande',
    category: 'supply_chain',
    calculation: '1 - (|Forecast - Actual| / Actual)',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'monthly',
    dimensions: ['product_category', 'time_horizon'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'logistics_return_rate',
    name: 'Product Return Rate',
    nameFr: 'Taux de retour produits',
    category: 'reverse_logistics',
    calculation: '(Returned items / Sold items) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['product_category', 'return_reason', 'channel'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
];

export default logisticsKPIs;
