/**
 * InsightGov Africa - Manufacturing & Industry KPI Templates
 * ============================================================
 * Indicateurs de performance pour le secteur manufacturier et industriel
 */

import { KPITemplateDefinition } from './health';

export const manufacturingKPIs: KPITemplateDefinition[] = [
  // PRODUCTION
  {
    id: 'manufacturing_production_volume',
    name: 'Production Volume',
    nameFr: 'Volume de production',
    category: 'production',
    calculation: 'Total units produced',
    unit: 'units',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 9.2',
    frequency: 'daily',
    dimensions: ['plant', 'product_line', 'shift'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_capacity_utilization',
    name: 'Capacity Utilization',
    nameFr: 'Utilisation de la capacité',
    category: 'production',
    calculation: '(Actual output / Maximum capacity) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    sdgAlignment: 'ODD 9.2',
    frequency: 'weekly',
    dimensions: ['plant', 'production_line'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'manufacturing_oee',
    name: 'Overall Equipment Effectiveness',
    nameFr: 'Efficacité globale équipements',
    category: 'production',
    calculation: 'Availability × Performance × Quality',
    unit: '%',
    format: 'percentage',
    target: 85,
    sdgAlignment: 'ODD 9.2',
    frequency: 'daily',
    dimensions: ['plant', 'equipment'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'manufacturing_cycle_time',
    name: 'Cycle Time',
    nameFr: 'Temps de cycle',
    category: 'production',
    calculation: 'Average time to complete one unit',
    unit: 'minutes',
    format: 'number',
    target: 10,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['plant', 'product'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_throughput',
    name: 'Throughput Rate',
    nameFr: 'Débit de production',
    category: 'production',
    calculation: 'Units produced per hour',
    unit: 'units/hour',
    format: 'number',
    target: 100,
    frequency: 'daily',
    dimensions: ['plant', 'line'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_yield',
    name: 'First Pass Yield',
    nameFr: 'Rendement premier passage',
    category: 'production',
    calculation: '(Good units / Total units) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'daily',
    dimensions: ['plant', 'product'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // QUALITY
  {
    id: 'manufacturing_defect_rate',
    name: 'Defect Rate',
    nameFr: 'Taux de défauts',
    category: 'quality',
    calculation: '(Defective units / Total units) × 100',
    unit: '%',
    format: 'percentage',
    target: 2,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['plant', 'product', 'defect_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'manufacturing_scrap_rate',
    name: 'Scrap Rate',
    nameFr: 'Taux de rebuts',
    category: 'quality',
    calculation: '(Scrap units / Total units) × 100',
    unit: '%',
    format: 'percentage',
    target: 1,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['plant', 'product'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'manufacturing_rework_rate',
    name: 'Rework Rate',
    nameFr: 'Taux de reprise',
    category: 'quality',
    calculation: '(Reworked units / Total units) × 100',
    unit: '%',
    format: 'percentage',
    target: 3,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['plant', 'product'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'manufacturing_customer_returns',
    name: 'Customer Return Rate',
    nameFr: 'Taux de retour client',
    category: 'quality',
    calculation: '(Returned products / Shipped products) × 100',
    unit: '%',
    format: 'percentage',
    target: 0.5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['product', 'return_reason'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'manufacturing_quality_cost',
    name: 'Cost of Quality',
    nameFr: 'Coût de la qualité',
    category: 'quality',
    calculation: '(Quality costs / Total production cost) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['plant', 'cost_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // MAINTENANCE
  {
    id: 'manufacturing_mtbf',
    name: 'Mean Time Between Failures',
    nameFr: 'MTBF',
    category: 'maintenance',
    calculation: 'Operating time / Number of failures',
    unit: 'hours',
    format: 'number',
    target: 500,
    frequency: 'monthly',
    dimensions: ['plant', 'equipment'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_mttr',
    name: 'Mean Time to Repair',
    nameFr: 'MTTR',
    category: 'maintenance',
    calculation: 'Total repair time / Number of repairs',
    unit: 'hours',
    format: 'number',
    target: 4,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['plant', 'equipment'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_availability',
    name: 'Equipment Availability',
    nameFr: 'Disponibilité équipements',
    category: 'maintenance',
    calculation: '(Uptime / (Uptime + Downtime)) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'weekly',
    dimensions: ['plant', 'equipment'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'manufacturing_planned_maintenance',
    name: 'Planned Maintenance Ratio',
    nameFr: 'Ratio maintenance planifiée',
    category: 'maintenance',
    calculation: '(Planned maintenance / Total maintenance) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'monthly',
    dimensions: ['plant'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'manufacturing_maintenance_cost',
    name: 'Maintenance Cost Ratio',
    nameFr: 'Ratio coût maintenance',
    category: 'maintenance',
    calculation: '(Maintenance cost / Asset value) × 100',
    unit: '%',
    format: 'percentage',
    target: 3,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['plant'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // INVENTORY
  {
    id: 'manufacturing_inventory_turnover',
    name: 'Inventory Turnover',
    nameFr: 'Rotation des stocks',
    category: 'inventory',
    calculation: 'Cost of goods sold / Average inventory',
    unit: 'ratio',
    format: 'ratio',
    target: 10,
    frequency: 'monthly',
    dimensions: ['plant', 'inventory_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_wip',
    name: 'Work-in-Progress Inventory',
    nameFr: 'En-cours de production',
    category: 'inventory',
    calculation: 'Value of WIP inventory',
    unit: 'USD',
    format: 'currency',
    target: 100000,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['plant'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_days_inventory',
    name: 'Days of Inventory',
    nameFr: 'Jours de stock',
    category: 'inventory',
    calculation: '(Inventory / Daily usage) × 1',
    unit: 'days',
    format: 'number',
    target: 15,
    frequency: 'monthly',
    dimensions: ['inventory_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_raw_material_availability',
    name: 'Raw Material Availability',
    nameFr: 'Disponibilité matières premières',
    category: 'inventory',
    calculation: '(Available materials / Required materials) × 100',
    unit: '%',
    format: 'percentage',
    target: 98,
    frequency: 'daily',
    dimensions: ['plant', 'material_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // EFFICIENCY
  {
    id: 'manufacturing_labor_productivity',
    name: 'Labor Productivity',
    nameFr: 'Productivité du travail',
    category: 'efficiency',
    calculation: 'Output units / Labor hours',
    unit: 'units/hour',
    format: 'number',
    target: 50,
    frequency: 'daily',
    dimensions: ['plant', 'department'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_energy_intensity',
    name: 'Energy Intensity',
    nameFr: 'Intensité énergétique',
    category: 'efficiency',
    calculation: 'Energy used / Units produced',
    unit: 'kWh/unit',
    format: 'number',
    target: 2,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 7.3',
    frequency: 'monthly',
    dimensions: ['plant', 'product'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_material_efficiency',
    name: 'Material Efficiency',
    nameFr: 'Efficacité matière',
    category: 'efficiency',
    calculation: '(Output weight / Input weight) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 12.2',
    frequency: 'monthly',
    dimensions: ['plant', 'product'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'manufacturing_setup_time',
    name: 'Average Setup Time',
    nameFr: 'Temps de changement moyen',
    category: 'efficiency',
    calculation: 'Average time for equipment changeover',
    unit: 'minutes',
    format: 'number',
    target: 30,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['plant', 'equipment'],
    visualization: { defaultType: 'kpi' }
  },

  // COST
  {
    id: 'manufacturing_unit_cost',
    name: 'Unit Production Cost',
    nameFr: 'Coût unitaire',
    category: 'cost',
    calculation: 'Total production cost / Units produced',
    unit: 'USD',
    format: 'currency',
    target: 10,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['plant', 'product'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_labor_cost_share',
    name: 'Labor Cost Share',
    nameFr: 'Part coût main d\'œuvre',
    category: 'cost',
    calculation: '(Labor cost / Total cost) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    frequency: 'monthly',
    dimensions: ['plant'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'manufacturing_overhead_rate',
    name: 'Overhead Rate',
    nameFr: 'Taux de frais généraux',
    category: 'cost',
    calculation: '(Overhead costs / Direct labor) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    frequency: 'monthly',
    dimensions: ['plant'],
    visualization: { defaultType: 'gauge' }
  },

  // DELIVERY
  {
    id: 'manufacturing_on_time_delivery',
    name: 'On-Time Delivery Rate',
    nameFr: 'Taux de livraison à temps',
    category: 'delivery',
    calculation: '(Orders delivered on time / Total orders) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 9.2',
    frequency: 'weekly',
    dimensions: ['plant', 'customer'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'manufacturing_lead_time',
    name: 'Manufacturing Lead Time',
    nameFr: 'Délai de fabrication',
    category: 'delivery',
    calculation: 'Average days from order to shipment',
    unit: 'days',
    format: 'number',
    target: 7,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['plant', 'product'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_order_fill_rate',
    name: 'Order Fill Rate',
    nameFr: 'Taux de satisfaction commandes',
    category: 'delivery',
    calculation: '(Complete shipments / Total orders) × 100',
    unit: '%',
    format: 'percentage',
    target: 98,
    frequency: 'weekly',
    dimensions: ['plant'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // SAFETY
  {
    id: 'manufacturing_ltir',
    name: 'Lost Time Injury Rate',
    nameFr: 'Taux d\'accidents avec arrêt',
    category: 'safety',
    calculation: '(LTI × 1,000,000) / Hours worked',
    unit: '/M hours',
    format: 'number',
    target: 1,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['plant', 'department'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_trir',
    name: 'Total Recordable Injury Rate',
    nameFr: 'Taux total d\'accidents',
    category: 'safety',
    calculation: '(TRI × 1,000,000) / Hours worked',
    unit: '/M hours',
    format: 'number',
    target: 2,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['plant'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_safety_incidents',
    name: 'Safety Incidents',
    nameFr: 'Incidents de sécurité',
    category: 'safety',
    calculation: 'Total safety incidents reported',
    unit: 'incidents',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['plant', 'incident_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_near_misses',
    name: 'Near Miss Reports',
    nameFr: 'Presque-accidents rapportés',
    category: 'safety',
    calculation: 'Total near miss reports',
    unit: 'reports',
    format: 'number',
    target: 100,
    frequency: 'monthly',
    dimensions: ['plant'],
    visualization: { defaultType: 'kpi' }
  },

  // SUSTAINABILITY
  {
    id: 'manufacturing_waste_recycling',
    name: 'Waste Recycling Rate',
    nameFr: 'Taux de recyclage déchets',
    category: 'sustainability',
    calculation: '(Recycled waste / Total waste) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 12.5',
    frequency: 'monthly',
    dimensions: ['plant', 'waste_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'manufacturing_water_usage',
    name: 'Water Usage Intensity',
    nameFr: 'Intensité usage d\'eau',
    category: 'sustainability',
    calculation: 'Water used / Units produced',
    unit: 'liters/unit',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 6.4',
    frequency: 'monthly',
    dimensions: ['plant'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'manufacturing_co2_emissions',
    name: 'CO2 Emissions Intensity',
    nameFr: 'Intensité émissions CO2',
    category: 'sustainability',
    calculation: 'CO2 emitted / Units produced',
    unit: 'kg CO2/unit',
    format: 'number',
    target: 1,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.2',
    frequency: 'monthly',
    dimensions: ['plant'],
    visualization: { defaultType: 'kpi' }
  },
];

export default manufacturingKPIs;
