/**
 * InsightGov Africa - Mining & Extractive Industries KPI Templates
 * ==================================================================
 * Indicateurs de performance pour le secteur minier et extractif
 */

import { KPITemplateDefinition } from './health';

export const miningKPIs: KPITemplateDefinition[] = [
  // PRODUCTION
  {
    id: 'mining_production_volume',
    name: 'Mineral Production Volume',
    nameFr: 'Volume de production minérale',
    category: 'production',
    calculation: 'Total tonnes of mineral extracted',
    unit: 'tonnes',
    format: 'number',
    target: 1000000,
    sdgAlignment: 'ODD 12.2',
    frequency: 'monthly',
    dimensions: ['mineral_type', 'mine', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_recovery_rate',
    name: 'Mineral Recovery Rate',
    nameFr: 'Taux de récupération',
    category: 'production',
    calculation: '(Extracted mineral / Total ore) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    frequency: 'monthly',
    dimensions: ['mineral_type', 'mine'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'mining_grade',
    name: 'Average Ore Grade',
    nameFr: 'Teneur moyenne',
    category: 'production',
    calculation: 'Average mineral content in ore',
    unit: 'g/tonne',
    format: 'number',
    target: 5,
    frequency: 'monthly',
    dimensions: ['mineral_type', 'mine'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_strip_ratio',
    name: 'Strip Ratio',
    nameFr: 'Ratio de découverte',
    category: 'production',
    calculation: 'Waste tonnes / Ore tonnes',
    unit: 'ratio',
    format: 'ratio',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['mine', 'pit'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_capacity_utilization',
    name: 'Capacity Utilization',
    nameFr: 'Utilisation de la capacité',
    category: 'production',
    calculation: '(Actual production / Design capacity) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'monthly',
    dimensions: ['mine', 'facility'],
    visualization: { defaultType: 'gauge' }
  },

  // OPERATIONAL EFFICIENCY
  {
    id: 'mining_equipment_availability',
    name: 'Equipment Availability',
    nameFr: 'Disponibilité des équipements',
    category: 'operations',
    calculation: '(Operating hours / Scheduled hours) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    frequency: 'daily',
    dimensions: ['equipment_type', 'mine'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'mining_tonnage_per_hour',
    name: 'Tonnage per Operating Hour',
    nameFr: 'Tonnage par heure opérationnelle',
    category: 'operations',
    calculation: 'Total tonnes / Operating hours',
    unit: 'tonnes/hour',
    format: 'number',
    target: 500,
    frequency: 'daily',
    dimensions: ['mine', 'equipment_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_truck_cycle_time',
    name: 'Truck Cycle Time',
    nameFr: 'Cycle camion',
    category: 'operations',
    calculation: 'Average time for truck cycle (load-haul-dump-return)',
    unit: 'minutes',
    format: 'number',
    target: 30,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['mine', 'route'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_downtime_rate',
    name: 'Unplanned Downtime Rate',
    nameFr: 'Taux d\'arrêt non planifié',
    category: 'operations',
    calculation: '(Unplanned downtime / Total scheduled time) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['mine', 'equipment_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'mining_maintenance_efficiency',
    name: 'Maintenance Efficiency',
    nameFr: 'Efficacité de maintenance',
    category: 'operations',
    calculation: '(Planned maintenance / Total maintenance) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'monthly',
    dimensions: ['mine'],
    visualization: { defaultType: 'gauge' }
  },

  // SAFETY
  {
    id: 'mining_ltir',
    name: 'Lost Time Injury Rate',
    nameFr: 'Taux d\'accidents avec arrêt',
    category: 'safety',
    calculation: '(LTI × 1,000,000) / Hours worked',
    unit: '/M hours',
    format: 'number',
    target: 0.5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['mine', 'operation_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_trir',
    name: 'Total Recordable Injury Rate',
    nameFr: 'Taux total d\'accidents',
    category: 'safety',
    calculation: '(TRI × 1,000,000) / Hours worked',
    unit: '/M hours',
    format: 'number',
    target: 1,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'monthly',
    dimensions: ['mine'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_fatalities',
    name: 'Fatality Rate',
    nameFr: 'Taux de mortalité',
    category: 'safety',
    calculation: 'Fatalities per year',
    unit: 'deaths',
    format: 'number',
    target: 0,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 8.8',
    frequency: 'annual',
    dimensions: ['mine'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_safety_incidents',
    name: 'Safety Incident Rate',
    nameFr: 'Taux d\'incidents de sécurité',
    category: 'safety',
    calculation: '(Incidents × 1,000) / Employees',
    unit: '/1,000 emp',
    format: 'number',
    target: 10,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['mine', 'incident_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_safety_training',
    name: 'Safety Training Compliance',
    nameFr: 'Conformité formation sécurité',
    category: 'safety',
    calculation: '(Employees trained / Total employees) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 8.8',
    frequency: 'quarterly',
    dimensions: ['mine', 'training_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // ENVIRONMENTAL
  {
    id: 'mining_water_usage',
    name: 'Water Usage Intensity',
    nameFr: 'Intensité d\'utilisation d\'eau',
    category: 'environment',
    calculation: 'Water used / Tonnes processed',
    unit: 'm³/tonne',
    format: 'number',
    target: 0.5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 6.4',
    frequency: 'monthly',
    dimensions: ['mine', 'process_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_water_recycling',
    name: 'Water Recycling Rate',
    nameFr: 'Taux de recyclage d\'eau',
    category: 'environment',
    calculation: '(Recycled water / Total water used) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 6.4',
    frequency: 'monthly',
    dimensions: ['mine'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'mining_energy_intensity',
    name: 'Energy Intensity',
    nameFr: 'Intensité énergétique',
    category: 'environment',
    calculation: 'Energy consumed / Tonnes produced',
    unit: 'GJ/tonne',
    format: 'number',
    target: 0.2,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 7.3',
    frequency: 'monthly',
    dimensions: ['mine', 'energy_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_co2_emissions',
    name: 'CO2 Emissions Intensity',
    nameFr: 'Intensité émissions CO2',
    category: 'environment',
    calculation: 'CO2 emitted / Tonnes produced',
    unit: 'kg CO2/tonne',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.2',
    frequency: 'monthly',
    dimensions: ['mine', 'source'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_land_rehabilitation',
    name: 'Land Rehabilitation Rate',
    nameFr: 'Taux de réhabilitation',
    category: 'environment',
    calculation: '(Rehabilitated area / Disturbed area) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 15.3',
    frequency: 'annual',
    dimensions: ['mine'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'mining_tailings_management',
    name: 'Tailings Facility Compliance',
    nameFr: 'Conformité installations tailings',
    category: 'environment',
    calculation: '(Compliant facilities / Total facilities) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    frequency: 'annual',
    dimensions: ['mine'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // FINANCIAL
  {
    id: 'mining_cost_per_tonne',
    name: 'Operating Cost per Tonne',
    nameFr: 'Coût opérationnel par tonne',
    category: 'financial',
    calculation: 'Total operating costs / Tonnes produced',
    unit: 'USD/tonne',
    format: 'currency',
    target: 50,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['mine', 'cost_category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_revenue_per_tonne',
    name: 'Revenue per Tonne',
    nameFr: 'Revenu par tonne',
    category: 'financial',
    calculation: 'Total revenue / Tonnes sold',
    unit: 'USD/tonne',
    format: 'currency',
    target: 150,
    frequency: 'monthly',
    dimensions: ['mine', 'mineral_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_operating_margin',
    name: 'Operating Margin',
    nameFr: 'Marge opérationnelle',
    category: 'financial',
    calculation: '(Revenue - Operating costs) / Revenue × 100',
    unit: '%',
    format: 'percentage',
    target: 40,
    frequency: 'quarterly',
    dimensions: ['mine', 'mineral_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'mining_royalty_revenue',
    name: 'Government Royalty Revenue',
    nameFr: 'Revenus royalties gouvernement',
    category: 'financial',
    calculation: 'Total royalties collected',
    unit: 'USD',
    format: 'currency',
    target: 100000000,
    sdgAlignment: 'ODD 17.1',
    frequency: 'annual',
    dimensions: ['mineral_type', 'company'],
    visualization: { defaultType: 'kpi' }
  },

  // EMPLOYMENT
  {
    id: 'mining_employment_total',
    name: 'Total Mining Employment',
    nameFr: 'Emploi minier total',
    category: 'employment',
    calculation: 'Total employees in mining sector',
    unit: 'employees',
    format: 'number',
    target: 50000,
    sdgAlignment: 'ODD 8.5',
    frequency: 'annual',
    dimensions: ['mine_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'mining_local_employment',
    name: 'Local Employment Rate',
    nameFr: 'Taux d\'emploi local',
    category: 'employment',
    calculation: '(Local employees / Total employees) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 8.5',
    frequency: 'annual',
    dimensions: ['mine', 'skill_level'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'mining_women_employment',
    name: 'Female Employment Rate',
    nameFr: 'Taux d\'emploi féminin',
    category: 'employment',
    calculation: '(Female employees / Total employees) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    sdgAlignment: 'ODD 5.1',
    frequency: 'annual',
    dimensions: ['mine', 'job_category'],
    visualization: { defaultType: 'gauge' }
  },

  // LOCAL CONTENT
  {
    id: 'mining_local_procurement',
    name: 'Local Procurement Rate',
    nameFr: 'Taux d\'achats locaux',
    category: 'local_content',
    calculation: '(Local purchases / Total purchases) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 9.2',
    frequency: 'annual',
    dimensions: ['mine', 'category'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'mining_community_investment',
    name: 'Community Investment',
    nameFr: 'Investissement communautaire',
    category: 'local_content',
    calculation: 'Total community investment / Revenue × 100',
    unit: '%',
    format: 'percentage',
    target: 1,
    frequency: 'annual',
    dimensions: ['mine', 'investment_type'],
    visualization: { defaultType: 'gauge' }
  },
];

export default miningKPIs;
