/**
 * InsightGov Africa - Police & Internal Security KPI Templates
 * ==============================================================
 * Indicateurs de performance pour la police et la sécurité intérieure
 */

import { KPITemplateDefinition } from './health';

export const policeKPIs: KPITemplateDefinition[] = [
  // CRIME STATISTICS
  {
    id: 'police_crime_rate',
    name: 'Overall Crime Rate',
    nameFr: 'Taux de criminalité global',
    category: 'crime',
    calculation: '(Reported crimes / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 500,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'monthly',
    dimensions: ['region', 'crime_type', 'urban_rural'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_violent_crime',
    name: 'Violent Crime Rate',
    nameFr: 'Taux de crimes violents',
    category: 'crime',
    calculation: '(Violent crimes / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 100,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'monthly',
    dimensions: ['region', 'crime_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_homicide_rate',
    name: 'Homicide Rate',
    nameFr: 'Taux d\'homicides',
    category: 'crime',
    calculation: '(Homicides / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'annual',
    dimensions: ['region', 'cause'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_property_crime',
    name: 'Property Crime Rate',
    nameFr: 'Taux de crimes contre les biens',
    category: 'crime',
    calculation: '(Property crimes / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 300,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['region', 'crime_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_robbery_rate',
    name: 'Robbery Rate',
    nameFr: 'Taux de vols à main armée',
    category: 'crime',
    calculation: '(Robberies / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_theft_rate',
    name: 'Theft Rate',
    nameFr: 'Taux de vols',
    category: 'crime',
    calculation: '(Thefts / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 200,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['region', 'theft_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_drug_offenses',
    name: 'Drug Offense Rate',
    nameFr: 'Taux d\'infractions drogues',
    category: 'crime',
    calculation: '(Drug offenses / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'monthly',
    dimensions: ['region', 'drug_type'],
    visualization: { defaultType: 'kpi' }
  },

  // RESPONSE TIMES
  {
    id: 'police_response_emergency',
    name: 'Emergency Response Time',
    nameFr: 'Temps de réponse urgence',
    category: 'response',
    calculation: 'Average minutes to respond to emergency calls',
    unit: 'minutes',
    format: 'number',
    target: 10,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'monthly',
    dimensions: ['region', 'call_type', 'urban_rural'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_response_priority',
    name: 'Priority Call Response Time',
    nameFr: 'Temps réponse appels prioritaires',
    category: 'response',
    calculation: 'Average minutes to respond to priority 1 calls',
    unit: 'minutes',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_response_compliance',
    name: 'Response Time Compliance',
    nameFr: 'Conformité temps de réponse',
    category: 'response',
    calculation: '(Calls responded within target / Total calls) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    frequency: 'monthly',
    dimensions: ['region', 'call_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'police_dispatch_time',
    name: 'Average Dispatch Time',
    nameFr: 'Temps moyen de dispatching',
    category: 'response',
    calculation: 'Average time from call to unit dispatch',
    unit: 'minutes',
    format: 'number',
    target: 2,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },

  // CASE RESOLUTION
  {
    id: 'police_clearance_rate',
    name: 'Case Clearance Rate',
    nameFr: 'Taux d\'élucidation',
    category: 'investigation',
    calculation: '(Cases cleared / Cases reported) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 16.3',
    frequency: 'monthly',
    dimensions: ['crime_type', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'police_homicide_clearance',
    name: 'Homicide Clearance Rate',
    nameFr: 'Taux d\'élucidation homicides',
    category: 'investigation',
    calculation: '(Homicides solved / Homicides reported) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'police_case_backlog',
    name: 'Case Backlog Rate',
    nameFr: 'Taux d\'arriéré d\'affaires',
    category: 'investigation',
    calculation: '(Pending cases / Total cases) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['crime_type', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'police_conviction_rate',
    name: 'Conviction Rate',
    nameFr: 'Taux de condamnation',
    category: 'investigation',
    calculation: '(Convictions / Prosecutions) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    sdgAlignment: 'ODD 16.3',
    frequency: 'annual',
    dimensions: ['crime_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'police_investigation_time',
    name: 'Average Investigation Time',
    nameFr: 'Durée moyenne d\'enquête',
    category: 'investigation',
    calculation: 'Average days to complete investigation',
    unit: 'days',
    format: 'number',
    target: 30,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['crime_type'],
    visualization: { defaultType: 'kpi' }
  },

  // PATROL & PRESENCE
  {
    id: 'police_patrol_hours',
    name: 'Patrol Hours per Officer',
    nameFr: 'Heures de patrouille par agent',
    category: 'patrol',
    calculation: 'Total patrol hours / Total officers',
    unit: 'hours/officer',
    format: 'number',
    target: 120,
    frequency: 'monthly',
    dimensions: ['region', 'shift'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_visibility_index',
    name: 'Police Visibility Index',
    nameFr: 'Indice de visibilité policière',
    category: 'patrol',
    calculation: 'Composite score of patrol presence',
    unit: 'index',
    format: 'number',
    target: 75,
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'police_patrol_coverage',
    name: 'Patrol Coverage Area',
    nameFr: 'Couverture de patrouille',
    category: 'patrol',
    calculation: 'Percentage of area regularly patrolled',
    unit: '%',
    format: 'percentage',
    target: 90,
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'police_community_contacts',
    name: 'Community Contacts',
    nameFr: 'Contacts communautaires',
    category: 'patrol',
    calculation: 'Positive citizen interactions per officer',
    unit: 'contacts/officer',
    format: 'number',
    target: 50,
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },

  // PERSONNEL
  {
    id: 'police_per_capita',
    name: 'Police per Capita',
    nameFr: 'Policiers par habitant',
    category: 'personnel',
    calculation: '(Police officers / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 300,
    sdgAlignment: 'ODD 16.1',
    frequency: 'annual',
    dimensions: ['region', 'urban_rural'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_vacancy_rate',
    name: 'Vacancy Rate',
    nameFr: 'Taux de vacance',
    category: 'personnel',
    calculation: '(Vacant positions / Total positions) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['rank', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'police_overtime_hours',
    name: 'Overtime Hours per Officer',
    nameFr: 'Heures supplémentaires par agent',
    category: 'personnel',
    calculation: 'Total overtime hours / Total officers',
    unit: 'hours/officer',
    format: 'number',
    target: 20,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_sick_leave',
    name: 'Sick Leave Rate',
    nameFr: 'Taux d\'absentéisme maladie',
    category: 'personnel',
    calculation: '(Sick days / Total work days) × 100',
    unit: '%',
    format: 'percentage',
    target: 3,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['rank', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'police_training_hours',
    name: 'Training Hours per Officer',
    nameFr: 'Heures de formation par agent',
    category: 'personnel',
    calculation: 'Total training hours / Total officers',
    unit: 'hours/officer',
    format: 'number',
    target: 40,
    sdgAlignment: 'ODD 16.1',
    frequency: 'annual',
    dimensions: ['training_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_women_share',
    name: 'Female Officers Share',
    nameFr: 'Part des policières',
    category: 'personnel',
    calculation: '(Female officers / Total officers) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 5.1',
    frequency: 'annual',
    dimensions: ['rank'],
    visualization: { defaultType: 'gauge' }
  },

  // PUBLIC SATISFACTION
  {
    id: 'police_satisfaction',
    name: 'Public Satisfaction Rate',
    nameFr: 'Taux de satisfaction public',
    category: 'community',
    calculation: '(Satisfied citizens / Surveyed) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    sdgAlignment: 'ODD 16.6',
    frequency: 'annual',
    dimensions: ['region', 'service_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'police_trust_index',
    name: 'Public Trust Index',
    nameFr: 'Indice de confiance publique',
    category: 'community',
    calculation: 'Composite score from public surveys',
    unit: 'index',
    format: 'number',
    target: 65,
    sdgAlignment: 'ODD 16.6',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'police_complaints',
    name: 'Complaints per Officer',
    nameFr: 'Plaintes par agent',
    category: 'community',
    calculation: '(Complaints / Total officers) × 100',
    unit: '/100 officers',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: ['complaint_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_complaint_resolution',
    name: 'Complaint Resolution Rate',
    nameFr: 'Taux de résolution plaintes',
    category: 'community',
    calculation: '(Resolved complaints / Total complaints) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    frequency: 'annual',
    dimensions: ['complaint_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'police_fear_crime',
    name: 'Fear of Crime Index',
    nameFr: 'Indice de peur du crime',
    category: 'community',
    calculation: 'Composite score from public surveys',
    unit: 'index',
    format: 'number',
    target: 30,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 16.1',
    frequency: 'annual',
    dimensions: ['region', 'gender'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // RESOURCE EFFICIENCY
  {
    id: 'police_cost_per_capita',
    name: 'Policing Cost per Capita',
    nameFr: 'Coût policier par habitant',
    category: 'resources',
    calculation: 'Total policing costs / Population',
    unit: 'USD',
    format: 'currency',
    target: 100,
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_cost_per_case',
    name: 'Cost per Case',
    nameFr: 'Coût par affaire',
    category: 'resources',
    calculation: 'Total costs / Cases handled',
    unit: 'USD',
    format: 'currency',
    target: 500,
    frequency: 'annual',
    dimensions: ['crime_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'police_vehicle_utilization',
    name: 'Vehicle Utilization Rate',
    nameFr: 'Taux d\'utilisation véhicules',
    category: 'resources',
    calculation: '(Vehicles in use / Total vehicles) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'monthly',
    dimensions: ['vehicle_type', 'region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'police_equipment_modern',
    name: 'Modern Equipment Rate',
    nameFr: 'Taux d\'équipements modernes',
    category: 'resources',
    calculation: '(Modern equipment / Total equipment) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    frequency: 'annual',
    dimensions: ['equipment_type'],
    visualization: { defaultType: 'gauge' }
  },
];

export default policeKPIs;
