/**
 * InsightGov Africa - Retail & Commerce KPI Templates
 * =====================================================
 * Indicateurs de performance pour le secteur du commerce et de la distribution
 */

import { KPITemplateDefinition } from './health';

export const retailKPIs: KPITemplateDefinition[] = [
  // SALES PERFORMANCE
  {
    id: 'retail_sales_revenue',
    name: 'Total Sales Revenue',
    nameFr: 'Chiffre d\'affaires total',
    category: 'sales',
    calculation: 'Sum of all sales',
    unit: 'USD',
    format: 'currency',
    target: 1000000,
    frequency: 'daily',
    dimensions: ['store', 'channel', 'category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_sales_growth',
    name: 'Sales Growth Rate',
    nameFr: 'Taux de croissance des ventes',
    category: 'sales',
    calculation: '((Current - Previous) / Previous) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    frequency: 'monthly',
    dimensions: ['store', 'channel', 'category'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'retail_sales_per_sqm',
    name: 'Sales per Square Meter',
    nameFr: 'Ventes au m²',
    category: 'sales',
    calculation: 'Total sales / Total selling area',
    unit: 'USD/m²',
    format: 'currency',
    target: 5000,
    frequency: 'monthly',
    dimensions: ['store', 'format'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_sales_per_employee',
    name: 'Sales per Employee',
    nameFr: 'Ventes par employé',
    category: 'sales',
    calculation: 'Total sales / Total employees',
    unit: 'USD/employee',
    format: 'currency',
    target: 100000,
    frequency: 'monthly',
    dimensions: ['store', 'department'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_transaction_value',
    name: 'Average Transaction Value',
    nameFr: 'Panier moyen',
    category: 'sales',
    calculation: 'Total sales / Number of transactions',
    unit: 'USD',
    format: 'currency',
    target: 50,
    frequency: 'daily',
    dimensions: ['store', 'channel'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_items_per_basket',
    name: 'Items per Basket',
    nameFr: 'Articles par panier',
    category: 'sales',
    calculation: 'Total items sold / Number of transactions',
    unit: 'items',
    format: 'number',
    target: 5,
    frequency: 'daily',
    dimensions: ['store', 'channel'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_foot_traffic',
    name: 'Store Foot Traffic',
    nameFr: 'Fréquentation magasin',
    category: 'sales',
    calculation: 'Total visitors to store',
    unit: 'visitors',
    format: 'number',
    target: 10000,
    frequency: 'daily',
    dimensions: ['store', 'period'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_conversion_rate',
    name: 'Conversion Rate',
    nameFr: 'Taux de conversion',
    category: 'sales',
    calculation: '(Transactions / Visitors) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    frequency: 'daily',
    dimensions: ['store', 'channel'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'retail_same_store_sales',
    name: 'Same-Store Sales Growth',
    nameFr: 'Croissance magasins comparables',
    category: 'sales',
    calculation: '((Current SSS - Previous SSS) / Previous SSS) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    frequency: 'monthly',
    dimensions: ['store_format'],
    visualization: { defaultType: 'gauge' }
  },

  // INVENTORY
  {
    id: 'retail_inventory_turnover',
    name: 'Inventory Turnover',
    nameFr: 'Rotation des stocks',
    category: 'inventory',
    calculation: 'Cost of goods sold / Average inventory',
    unit: 'ratio',
    format: 'ratio',
    target: 8,
    frequency: 'monthly',
    dimensions: ['store', 'category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_stockout_rate',
    name: 'Stock-out Rate',
    nameFr: 'Taux de rupture',
    category: 'inventory',
    calculation: '(Out-of-stock items / Total SKUs) × 100',
    unit: '%',
    format: 'percentage',
    target: 2,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['store', 'category'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'retail_inventory_accuracy',
    name: 'Inventory Accuracy',
    nameFr: 'Précision des stocks',
    category: 'inventory',
    calculation: '(Accurate counts / Total counts) × 100',
    unit: '%',
    format: 'percentage',
    target: 98,
    frequency: 'monthly',
    dimensions: ['store', 'category'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'retail_days_inventory',
    name: 'Days of Inventory',
    nameFr: 'Jours de stock',
    category: 'inventory',
    calculation: '(Average inventory / COGS) × 365',
    unit: 'days',
    format: 'number',
    target: 45,
    frequency: 'monthly',
    dimensions: ['category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_shrinkage_rate',
    name: 'Shrinkage Rate',
    nameFr: 'Taux de démarque inconnue',
    category: 'inventory',
    calculation: '(Inventory loss / Sales) × 100',
    unit: '%',
    format: 'percentage',
    target: 1,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['store', 'category', 'cause'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'retail_gross_margin',
    name: 'Gross Margin',
    nameFr: 'Marge brute',
    category: 'profitability',
    calculation: '((Sales - COGS) / Sales) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    frequency: 'monthly',
    dimensions: ['store', 'category'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'retail_markdown_rate',
    name: 'Markdown Rate',
    nameFr: 'Taux de démarque',
    category: 'inventory',
    calculation: '(Markdown amount / Original price) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['category', 'season'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // CUSTOMER
  {
    id: 'retail_customer_count',
    name: 'Customer Count',
    nameFr: 'Nombre de clients',
    category: 'customer',
    calculation: 'Unique customers served',
    unit: 'customers',
    format: 'number',
    target: 50000,
    frequency: 'monthly',
    dimensions: ['store', 'channel'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_customer_retention',
    name: 'Customer Retention Rate',
    nameFr: 'Taux de fidélisation',
    category: 'customer',
    calculation: '(Returning customers / Total customers) × 100',
    unit: '%',
    format: 'percentage',
    target: 60,
    frequency: 'monthly',
    dimensions: ['store', 'segment'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'retail_repeat_purchase',
    name: 'Repeat Purchase Rate',
    nameFr: 'Taux de réachat',
    category: 'customer',
    calculation: '(Customers with 2+ purchases / Total customers) × 100',
    unit: '%',
    format: 'percentage',
    target: 40,
    frequency: 'monthly',
    dimensions: ['store', 'channel'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'retail_customer_lifetime_value',
    name: 'Customer Lifetime Value',
    nameFr: 'Valeur vie client',
    category: 'customer',
    calculation: 'Average purchase value × Purchase frequency × Lifespan',
    unit: 'USD',
    format: 'currency',
    target: 1000,
    frequency: 'annual',
    dimensions: ['segment', 'channel'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_nps',
    name: 'Net Promoter Score',
    nameFr: 'Score Net Promoter',
    category: 'customer',
    calculation: '% Promoters - % Detractors',
    unit: 'score',
    format: 'number',
    target: 50,
    frequency: 'quarterly',
    dimensions: ['store', 'channel'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'retail_customer_satisfaction',
    name: 'Customer Satisfaction Score',
    nameFr: 'Score de satisfaction client',
    category: 'customer',
    calculation: '(Satisfied customers / Surveyed) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'monthly',
    dimensions: ['store', 'department'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'retail_return_rate',
    name: 'Product Return Rate',
    nameFr: 'Taux de retour produits',
    category: 'customer',
    calculation: '(Returned items / Sold items) × 100',
    unit: '%',
    format: 'percentage',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['category', 'return_reason'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // EMPLOYEES
  {
    id: 'retail_employee_productivity',
    name: 'Employee Productivity',
    nameFr: 'Productivité employés',
    category: 'hr',
    calculation: 'Sales / Labor hours',
    unit: 'USD/hour',
    format: 'currency',
    target: 100,
    frequency: 'weekly',
    dimensions: ['store', 'department'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_labor_cost_ratio',
    name: 'Labor Cost Ratio',
    nameFr: 'Ratio coût travail',
    category: 'hr',
    calculation: '(Labor costs / Sales) × 100',
    unit: '%',
    format: 'percentage',
    target: 15,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['store'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'retail_turnover_rate',
    name: 'Employee Turnover Rate',
    nameFr: 'Taux de rotation personnel',
    category: 'hr',
    calculation: '(Departures / Average workforce) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    lowerIsBetter: true,
    frequency: 'annual',
    dimensions: ['store', 'position'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'retail_absenteeism',
    name: 'Absenteeism Rate',
    nameFr: 'Taux d\'absentéisme',
    category: 'hr',
    calculation: '(Absent days / Scheduled days) × 100',
    unit: '%',
    format: 'percentage',
    target: 3,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['store'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'retail_training_hours',
    name: 'Training Hours per Employee',
    nameFr: 'Heures formation par employé',
    category: 'hr',
    calculation: 'Total training hours / Total employees',
    unit: 'hours',
    format: 'number',
    target: 20,
    frequency: 'annual',
    dimensions: ['store', 'position'],
    visualization: { defaultType: 'kpi' }
  },

  // E-COMMERCE (for omnichannel)
  {
    id: 'retail_online_sales_share',
    name: 'Online Sales Share',
    nameFr: 'Part des ventes en ligne',
    category: 'ecommerce',
    calculation: '(Online sales / Total sales) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    frequency: 'monthly',
    dimensions: ['category'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'retail_cart_abandonment',
    name: 'Cart Abandonment Rate',
    nameFr: 'Taux d\'abandon panier',
    category: 'ecommerce',
    calculation: '(Abandoned carts / Total carts) × 100',
    unit: '%',
    format: 'percentage',
    target: 60,
    lowerIsBetter: true,
    frequency: 'weekly',
    dimensions: ['device', 'channel'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'retail_website_traffic',
    name: 'Website Traffic',
    nameFr: 'Trafic site web',
    category: 'ecommerce',
    calculation: 'Total website visits',
    unit: 'visits',
    format: 'number',
    target: 100000,
    frequency: 'weekly',
    dimensions: ['source', 'device'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_click_collect',
    name: 'Click & Collect Rate',
    nameFr: 'Taux Click & Collect',
    category: 'ecommerce',
    calculation: '(Click & Collect orders / Total online orders) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    frequency: 'monthly',
    dimensions: ['store'],
    visualization: { defaultType: 'gauge' }
  },

  // STORE OPERATIONS
  {
    id: 'retail_store_hours_utilization',
    name: 'Store Hours Utilization',
    nameFr: 'Utilisation heures ouverture',
    category: 'operations',
    calculation: '(Sales hours / Open hours) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    frequency: 'weekly',
    dimensions: ['store', 'day_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'retail_queue_time',
    name: 'Average Queue Time',
    nameFr: 'Temps d\'attente moyen',
    category: 'operations',
    calculation: 'Average customer wait time at checkout',
    unit: 'minutes',
    format: 'number',
    target: 3,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['store', 'period'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'retail_checkout_efficiency',
    name: 'Checkout Efficiency',
    nameFr: 'Efficacité caisses',
    calculation: 'Transactions per checkout hour',
    nameFr: 'Transactions par heure caisse',
    category: 'operations',
    unit: 'trans/hour',
    format: 'number',
    target: 25,
    frequency: 'daily',
    dimensions: ['store', 'checkout_type'],
    visualization: { defaultType: 'kpi' }
  },
];

export default retailKPIs;
