/**
 * InsightGov Africa - Telecommunications KPI Templates
 * ======================================================
 * Indicateurs de performance pour le secteur des télécommunications
 */

import { KPITemplateDefinition } from './health';

export const telecomKPIs: KPITemplateDefinition[] = [
  // NETWORK COVERAGE
  {
    id: 'telecom_population_coverage',
    name: 'Population Coverage',
    nameFr: 'Couverture population',
    category: 'coverage',
    calculation: '(Population covered / Total population) × 100',
    unit: '%',
    format: 'percentage',
    target: 99,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['technology', 'region', 'urban_rural'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'telecom_4g_coverage',
    name: '4G Coverage',
    nameFr: 'Couverture 4G',
    category: 'coverage',
    calculation: '(Population with 4G / Total population) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['region', 'urban_rural'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'telecom_5g_coverage',
    name: '5G Coverage',
    nameFr: 'Couverture 5G',
    category: 'coverage',
    calculation: '(Population with 5G / Total population) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'telecom_territorial_coverage',
    name: 'Geographic Coverage',
    nameFr: 'Couverture géographique',
    category: 'coverage',
    calculation: '(Area covered / Total area) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['technology', 'region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'telecom_rural_coverage',
    name: 'Rural Coverage',
    nameFr: 'Couverture rurale',
    category: 'coverage',
    calculation: '(Rural population covered / Rural population) × 100',
    unit: '%',
    format: 'percentage',
    target: 90,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // SUBSCRIBERS
  {
    id: 'telecom_subscribers',
    name: 'Total Subscribers',
    nameFr: 'Total abonnés',
    category: 'subscribers',
    calculation: 'Total active SIM cards',
    unit: 'subscribers',
    format: 'number',
    target: 20000000,
    sdgAlignment: 'ODD 9.c',
    frequency: 'monthly',
    dimensions: ['operator', 'technology'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_penetration_rate',
    name: 'Mobile Penetration Rate',
    nameFr: 'Taux de pénétration mobile',
    category: 'subscribers',
    calculation: '(Mobile subscribers / Population) × 100',
    unit: '%',
    format: 'percentage',
    target: 120,
    sdgAlignment: 'ODD 9.c',
    frequency: 'monthly',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'telecom_active_subscribers',
    name: 'Active Subscriber Rate',
    nameFr: 'Taux d\'abonnés actifs',
    category: 'subscribers',
    calculation: '(Active subscribers / Total subscribers) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'monthly',
    dimensions: ['operator'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'telecom_churn_rate',
    name: 'Churn Rate',
    nameFr: 'Taux de désabonnement',
    category: 'subscribers',
    calculation: '(Lost subscribers / Average subscribers) × 100',
    unit: '%',
    format: 'percentage',
    target: 3,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['operator', 'segment'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'telecom_data_subscribers',
    name: 'Data Subscriber Share',
    nameFr: 'Part abonnés data',
    category: 'subscribers',
    calculation: '(Data subscribers / Total subscribers) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    sdgAlignment: 'ODD 9.c',
    frequency: 'monthly',
    dimensions: ['operator'],
    visualization: { defaultType: 'gauge' }
  },

  // REVENUE
  {
    id: 'telecom_arpu',
    name: 'ARPU',
    nameFr: 'ARPU',
    category: 'revenue',
    calculation: 'Total revenue / Total subscribers',
    unit: 'USD/month',
    format: 'currency',
    target: 10,
    frequency: 'monthly',
    dimensions: ['operator', 'segment'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_revenue_total',
    name: 'Total Revenue',
    nameFr: 'Revenu total',
    category: 'revenue',
    calculation: 'Total telecom revenue',
    unit: 'USD',
    format: 'currency',
    target: 500000000,
    frequency: 'monthly',
    dimensions: ['operator', 'service_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_data_revenue_share',
    name: 'Data Revenue Share',
    nameFr: 'Part revenus data',
    category: 'revenue',
    calculation: '(Data revenue / Total revenue) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    frequency: 'monthly',
    dimensions: ['operator'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'telecom_voice_revenue_share',
    name: 'Voice Revenue Share',
    nameFr: 'Part revenus voix',
    category: 'revenue',
    calculation: '(Voice revenue / Total revenue) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    frequency: 'monthly',
    dimensions: ['operator'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'telecom_sms_revenue_share',
    name: 'SMS Revenue Share',
    nameFr: 'Part revenus SMS',
    category: 'revenue',
    calculation: '(SMS revenue / Total revenue) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    frequency: 'monthly',
    dimensions: ['operator'],
    visualization: { defaultType: 'gauge' }
  },

  // NETWORK QUALITY
  {
    id: 'telecom_call_success_rate',
    name: 'Call Success Rate',
    nameFr: 'Taux de succès d\'appel',
    category: 'quality',
    calculation: '(Successful calls / Attempted calls) × 100',
    unit: '%',
    format: 'percentage',
    target: 98,
    frequency: 'daily',
    dimensions: ['operator', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'telecom_call_drop_rate',
    name: 'Call Drop Rate',
    nameFr: 'Taux de coupure d\'appel',
    category: 'quality',
    calculation: '(Dropped calls / Established calls) × 100',
    unit: '%',
    format: 'percentage',
    target: 1,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['operator', 'region'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'telecom_download_speed',
    name: 'Average Download Speed',
    nameFr: 'Vitesse moyenne téléchargement',
    category: 'quality',
    calculation: 'Average Mbps download speed',
    unit: 'Mbps',
    format: 'number',
    target: 25,
    sdgAlignment: 'ODD 9.c',
    frequency: 'monthly',
    dimensions: ['operator', 'technology', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_upload_speed',
    name: 'Average Upload Speed',
    nameFr: 'Vitesse moyenne envoi',
    category: 'quality',
    calculation: 'Average Mbps upload speed',
    unit: 'Mbps',
    format: 'number',
    target: 10,
    sdgAlignment: 'ODD 9.c',
    frequency: 'monthly',
    dimensions: ['operator', 'technology'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_latency',
    name: 'Network Latency',
    nameFr: 'Latence réseau',
    category: 'quality',
    calculation: 'Average latency in milliseconds',
    unit: 'ms',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['operator', 'technology'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_throughput',
    name: 'Network Throughput',
    nameFr: 'Débit réseau',
    category: 'quality',
    calculation: 'Average data throughput per cell',
    unit: 'Mbps',
    format: 'number',
    target: 100,
    frequency: 'monthly',
    dimensions: ['operator', 'technology'],
    visualization: { defaultType: 'kpi' }
  },

  // INFRASTRUCTURE
  {
    id: 'telecom_towers',
    name: 'Total Towers',
    nameFr: 'Total pylônes',
    category: 'infrastructure',
    calculation: 'Total cell towers deployed',
    unit: 'towers',
    format: 'number',
    target: 5000,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_tower_sharing',
    name: 'Tower Sharing Rate',
    nameFr: 'Taux de partage pylônes',
    category: 'infrastructure',
    calculation: '(Shared towers / Total towers) × 100',
    unit: '%',
    format: 'percentage',
    target: 60,
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'telecom_fiber_length',
    name: 'Fiber Network Length',
    nameFr: 'Longueur fibre optique',
    category: 'infrastructure',
    calculation: 'Total km of fiber deployed',
    unit: 'km',
    format: 'number',
    target: 10000,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['region', 'type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_data_centers',
    name: 'Data Center Capacity',
    nameFr: 'Capacité centres de données',
    category: 'infrastructure',
    calculation: 'Total MW of data center capacity',
    unit: 'MW',
    format: 'number',
    target: 50,
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_base_station_power',
    name: 'Green Power Base Stations',
    nameFr: 'Stations vertes',
    category: 'infrastructure',
    calculation: '(Solar/hybrid stations / Total stations) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 7.2',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge' }
  },

  // SERVICE QUALITY
  {
    id: 'telecom_customer_satisfaction',
    name: 'Customer Satisfaction Score',
    nameFr: 'Score satisfaction client',
    category: 'service',
    calculation: '(Satisfied customers / Surveyed) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'quarterly',
    dimensions: ['operator', 'segment'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'telecom_nps',
    name: 'Net Promoter Score',
    nameFr: 'Score Net Promoter',
    category: 'service',
    calculation: '% Promoters - % Detractors',
    unit: 'score',
    format: 'number',
    target: 30,
    frequency: 'quarterly',
    dimensions: ['operator'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'telecom_complaint_rate',
    name: 'Complaint Rate',
    nameFr: 'Taux de réclamation',
    category: 'service',
    calculation: '(Complaints / 1000 subscribers) × 100',
    unit: '/1,000',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['operator', 'complaint_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_resolution_time',
    name: 'Complaint Resolution Time',
    nameFr: 'Délai résolution réclamation',
    category: 'service',
    calculation: 'Average hours to resolve complaints',
    unit: 'hours',
    format: 'number',
    target: 48,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['operator'],
    visualization: { defaultType: 'kpi' }
  },

  // INTERNET
  {
    id: 'telecom_internet_users',
    name: 'Internet Users',
    nameFr: 'Utilisateurs Internet',
    category: 'internet',
    calculation: 'Total internet users',
    unit: 'users',
    format: 'number',
    target: 15000000,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['connection_type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_internet_penetration',
    name: 'Internet Penetration Rate',
    nameFr: 'Taux de pénétration Internet',
    category: 'internet',
    calculation: '(Internet users / Population) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: ['region', 'urban_rural'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'telecom_broadband_subscribers',
    name: 'Broadband Subscribers',
    nameFr: 'Abonnés haut débit',
    category: 'internet',
    calculation: 'Total fixed broadband subscribers',
    unit: 'subscribers',
    format: 'number',
    target: 500000,
    sdgAlignment: 'ODD 9.c',
    frequency: 'monthly',
    dimensions: ['speed_tier', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_data_consumption',
    name: 'Average Data Consumption',
    nameFr: 'Consommation data moyenne',
    category: 'internet',
    calculation: 'Average GB per subscriber per month',
    unit: 'GB/month',
    format: 'number',
    target: 5,
    sdgAlignment: 'ODD 9.c',
    frequency: 'monthly',
    dimensions: ['operator', 'technology'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'telecom_affordability',
    name: 'Internet Affordability',
    nameFr: 'Abordabilité Internet',
    category: 'internet',
    calculation: '(1GB cost / Monthly GNI per capita) × 100',
    unit: '%',
    format: 'percentage',
    target: 2,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 9.c',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },

  // SECURITY
  {
    id: 'telecom_fraud_rate',
    name: 'Fraud Rate',
    nameFr: 'Taux de fraude',
    category: 'security',
    calculation: '(Fraud incidents / Total transactions) × 100',
    unit: '%',
    format: 'percentage',
    target: 0.1,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['operator', 'fraud_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'telecom_spam_rate',
    name: 'Spam SMS Rate',
    nameFr: 'Taux de spam SMS',
    category: 'security',
    calculation: '(Spam SMS / Total SMS) × 100',
    unit: '%',
    format: 'percentage',
    target: 2,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['operator'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'telecom_network_uptime',
    name: 'Network Uptime',
    nameFr: 'Disponibilité réseau',
    category: 'security',
    calculation: '(Uptime hours / Total hours) × 100',
    unit: '%',
    format: 'percentage',
    target: 99.9,
    frequency: 'monthly',
    dimensions: ['operator', 'network_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
];

export default telecomKPIs;
