/**
 * InsightGov Africa - Tourism & Hospitality KPI Templates
 * =========================================================
 * Indicateurs de performance pour le secteur du tourisme et de l'hôtellerie
 */

import { KPITemplateDefinition } from './health';

export const tourismKPIs: KPITemplateDefinition[] = [
  // TOURISM VOLUME
  {
    id: 'tourism_arrivals',
    name: 'Tourist Arrivals',
    nameFr: 'Arrivées touristiques',
    category: 'volume',
    calculation: 'Total international and domestic tourists',
    unit: 'visitors',
    format: 'number',
    target: 500000,
    sdgAlignment: 'ODD 8.9',
    frequency: 'monthly',
    dimensions: ['origin', 'purpose', 'point_of_entry'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_international_arrivals',
    name: 'International Tourist Arrivals',
    nameFr: 'Arrivées touristes internationaux',
    category: 'volume',
    calculation: 'Total international visitors',
    unit: 'visitors',
    format: 'number',
    target: 200000,
    sdgAlignment: 'ODD 8.9',
    frequency: 'monthly',
    dimensions: ['country', 'purpose'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_domestic_trips',
    name: 'Domestic Tourism Trips',
    nameFr: 'Voyages touristiques domestiques',
    category: 'volume',
    calculation: 'Total domestic tourist trips',
    unit: 'trips',
    format: 'number',
    target: 300000,
    sdgAlignment: 'ODD 8.9',
    frequency: 'monthly',
    dimensions: ['region', 'purpose'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_visitor_nights',
    name: 'Total Visitor Nights',
    nameFr: 'Nuitées totales',
    category: 'volume',
    calculation: 'Total nights spent by tourists',
    unit: 'nights',
    format: 'number',
    target: 2000000,
    sdgAlignment: 'ODD 8.9',
    frequency: 'monthly',
    dimensions: ['origin', 'region', 'accommodation_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_avg_stay',
    name: 'Average Length of Stay',
    nameFr: 'Durée moyenne de séjour',
    category: 'volume',
    calculation: 'Total nights / Total visitors',
    unit: 'nights',
    format: 'number',
    target: 5,
    frequency: 'monthly',
    dimensions: ['origin', 'purpose'],
    visualization: { defaultType: 'kpi' }
  },

  // ECONOMIC IMPACT
  {
    id: 'tourism_revenue',
    name: 'Tourism Revenue',
    nameFr: 'Revenus touristiques',
    category: 'economic',
    calculation: 'Total tourism expenditure',
    unit: 'USD',
    format: 'currency',
    target: 500000000,
    sdgAlignment: 'ODD 8.9',
    frequency: 'monthly',
    dimensions: ['source', 'category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_gdp_contribution',
    name: 'Tourism GDP Contribution',
    nameFr: 'Contribution tourisme au PIB',
    category: 'economic',
    calculation: '(Tourism GDP / Total GDP) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    sdgAlignment: 'ODD 8.9',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'tourism_revenue_per_visitor',
    name: 'Revenue per Visitor',
    nameFr: 'Revenu par visiteur',
    category: 'economic',
    calculation: 'Total tourism revenue / Total visitors',
    unit: 'USD',
    format: 'currency',
    target: 800,
    frequency: 'monthly',
    dimensions: ['origin', 'purpose'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_revenue_per_night',
    name: 'Revenue per Night',
    nameFr: 'Revenu par nuitée',
    category: 'economic',
    calculation: 'Total tourism revenue / Total nights',
    unit: 'USD',
    format: 'currency',
    target: 150,
    frequency: 'monthly',
    dimensions: ['region', 'accommodation_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_employment',
    name: 'Tourism Employment',
    nameFr: 'Emploi touristique',
    category: 'economic',
    calculation: 'Total jobs in tourism sector',
    unit: 'jobs',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 8.9',
    frequency: 'annual',
    dimensions: ['subsector', 'type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_export_share',
    name: 'Tourism Export Share',
    nameFr: 'Part exportations touristiques',
    category: 'economic',
    calculation: '(Tourism revenue / Total exports) × 100',
    unit: '%',
    format: 'percentage',
    target: 20,
    sdgAlignment: 'ODD 8.9',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'gauge' }
  },

  // ACCOMMODATION
  {
    id: 'tourism_occupancy_rate',
    name: 'Hotel Occupancy Rate',
    nameFr: 'Taux d\'occupation hôtellerie',
    category: 'accommodation',
    calculation: '(Occupied rooms / Available rooms) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    sdgAlignment: 'ODD 8.9',
    frequency: 'monthly',
    dimensions: ['region', 'hotel_category', 'season'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'tourism_adr',
    name: 'Average Daily Rate (ADR)',
    nameFr: 'Prix moyen journalier',
    category: 'accommodation',
    calculation: 'Total room revenue / Rooms sold',
    unit: 'USD',
    format: 'currency',
    target: 100,
    frequency: 'monthly',
    dimensions: ['region', 'hotel_category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_revpar',
    name: 'Revenue per Available Room (RevPAR)',
    nameFr: 'Revenu par chambre disponible',
    category: 'accommodation',
    calculation: 'Occupancy rate × ADR',
    unit: 'USD',
    format: 'currency',
    target: 70,
    frequency: 'monthly',
    dimensions: ['region', 'hotel_category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_hotel_capacity',
    name: 'Total Hotel Capacity',
    nameFr: 'Capacité hôtelière totale',
    category: 'accommodation',
    calculation: 'Total hotel rooms available',
    unit: 'rooms',
    format: 'number',
    target: 20000,
    frequency: 'annual',
    dimensions: ['region', 'category'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_guest_satisfaction',
    name: 'Guest Satisfaction Score',
    nameFr: 'Score satisfaction clients',
    category: 'accommodation',
    calculation: '(Satisfied guests / Surveyed guests) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'monthly',
    dimensions: ['hotel', 'category'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'tourism_repeat_guests',
    name: 'Repeat Guest Rate',
    nameFr: 'Taux de clients fidèles',
    category: 'accommodation',
    calculation: '(Returning guests / Total guests) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    frequency: 'annual',
    dimensions: ['hotel_category'],
    visualization: { defaultType: 'gauge' }
  },

  // ATTRACTIONS
  {
    id: 'tourism_attraction_visitors',
    name: 'Attraction Visitors',
    nameFr: 'Visiteurs attractions',
    category: 'attractions',
    calculation: 'Total visitors to tourist attractions',
    unit: 'visitors',
    format: 'number',
    target: 1000000,
    frequency: 'monthly',
    dimensions: ['attraction', 'type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_attraction_revenue',
    name: 'Attraction Revenue',
    nameFr: 'Revenus attractions',
    category: 'attractions',
    calculation: 'Total revenue from attractions',
    unit: 'USD',
    format: 'currency',
    target: 10000000,
    frequency: 'monthly',
    dimensions: ['attraction', 'type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_heritage_sites',
    name: 'UNESCO Sites Visited',
    nameFr: 'Sites UNESCO visités',
    category: 'attractions',
    calculation: 'Total visitors to UNESCO heritage sites',
    unit: 'visitors',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 8.9',
    frequency: 'annual',
    dimensions: ['site'],
    visualization: { defaultType: 'kpi' }
  },

  // TRANSPORT
  {
    id: 'tourism_air_passengers',
    name: 'Air Passenger Arrivals',
    nameFr: 'Passagers aériens',
    category: 'transport',
    calculation: 'Total air passenger arrivals',
    unit: 'passengers',
    format: 'number',
    target: 300000,
    frequency: 'monthly',
    dimensions: ['airport', 'airline', 'origin'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_cruise_passengers',
    name: 'Cruise Ship Passengers',
    nameFr: 'Passagers croisières',
    category: 'transport',
    calculation: 'Total cruise ship passenger arrivals',
    unit: 'passengers',
    format: 'number',
    target: 50000,
    frequency: 'monthly',
    dimensions: ['port', 'ship'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_charter_flights',
    name: 'Charter Flight Arrivals',
    nameFr: 'Vols charters',
    category: 'transport',
    calculation: 'Total charter flight arrivals',
    unit: 'flights',
    format: 'number',
    target: 200,
    frequency: 'monthly',
    dimensions: ['airport', 'origin'],
    visualization: { defaultType: 'kpi' }
  },

  // MARKETING
  {
    id: 'tourism_marketing_roi',
    name: 'Marketing ROI',
    nameFr: 'ROI marketing',
    category: 'marketing',
    calculation: '(Revenue from marketing - Marketing cost) / Marketing cost × 100',
    unit: '%',
    format: 'percentage',
    target: 300,
    frequency: 'annual',
    dimensions: ['campaign', 'channel'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'tourism_website_traffic',
    name: 'Tourism Website Traffic',
    nameFr: 'Trafic site touristique',
    category: 'marketing',
    calculation: 'Total visits to tourism website',
    unit: 'visits',
    format: 'number',
    target: 500000,
    frequency: 'monthly',
    dimensions: ['source', 'country'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_social_reach',
    name: 'Social Media Reach',
    nameFr: 'Portée réseaux sociaux',
    category: 'marketing',
    calculation: 'Total social media impressions',
    unit: 'impressions',
    format: 'number',
    target: 10000000,
    frequency: 'monthly',
    dimensions: ['platform'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_brand_awareness',
    name: 'Brand Awareness Index',
    nameFr: 'Indice notoriété',
    category: 'marketing',
    calculation: 'Composite score from surveys',
    unit: 'index',
    format: 'number',
    target: 70,
    frequency: 'annual',
    dimensions: ['market'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // SUSTAINABILITY
  {
    id: 'tourism_eco_certified',
    name: 'Eco-Certified Establishments',
    nameFr: 'Établissements éco-certifiés',
    category: 'sustainability',
    calculation: '(Eco-certified hotels / Total hotels) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    sdgAlignment: 'ODD 12.4',
    frequency: 'annual',
    dimensions: ['region', 'type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'tourism_waste_recycling',
    name: 'Tourism Waste Recycling Rate',
    nameFr: 'Taux recyclage déchets tourisme',
    category: 'sustainability',
    calculation: '(Recycled waste / Total waste) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    sdgAlignment: 'ODD 12.5',
    frequency: 'annual',
    dimensions: ['establishment_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'tourism_carbon_footprint',
    name: 'Tourism Carbon Footprint',
    nameFr: 'Empreinte carbone tourisme',
    category: 'sustainability',
    calculation: 'CO2 emissions per tourist',
    unit: 'kg CO2/tourist',
    format: 'number',
    target: 100,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 13.2',
    frequency: 'annual',
    dimensions: [],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_water_usage',
    name: 'Water Usage per Guest Night',
    nameFr: 'Consommation eau par nuitée',
    category: 'sustainability',
    calculation: 'Total water used / Total guest nights',
    unit: 'liters/night',
    format: 'number',
    target: 200,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 6.4',
    frequency: 'annual',
    dimensions: ['establishment_type'],
    visualization: { defaultType: 'kpi' }
  },

  // QUALITY & SATISFACTION
  {
    id: 'tourism_nps',
    name: 'Net Promoter Score',
    nameFr: 'Score Net Promoter',
    category: 'quality',
    calculation: '% Promoters - % Detractors',
    unit: 'score',
    format: 'number',
    target: 40,
    frequency: 'quarterly',
    dimensions: ['origin', 'purpose'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'tourism_tripadvisor_rating',
    name: 'Average TripAdvisor Rating',
    nameFr: 'Note TripAdvisor moyenne',
    category: 'quality',
    calculation: 'Average rating on TripAdvisor',
    unit: 'rating',
    format: 'number',
    target: 4.5,
    frequency: 'monthly',
    dimensions: ['attraction_type', 'region'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'tourism_complaint_rate',
    name: 'Tourist Complaint Rate',
    nameFr: 'Taux de plaintes touristes',
    category: 'quality',
    calculation: '(Complaints / Total tourists) × 1000',
    unit: '/1,000',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['category', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'tourism_safety_perception',
    name: 'Safety Perception Index',
    nameFr: 'Indice de perception sécurité',
    category: 'quality',
    calculation: 'Composite score from surveys',
    unit: 'index',
    format: 'number',
    target: 80,
    sdgAlignment: 'ODD 16.1',
    frequency: 'annual',
    dimensions: ['origin'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
];

export default tourismKPIs;
