/**
 * InsightGov Africa - Transport & Mobility KPI Templates
 * ========================================================
 * Indicateurs de performance pour le secteur du transport et de la mobilité
 */

import { KPITemplateDefinition } from './health';

export const transportKPIs: KPITemplateDefinition[] = [
  // PUBLIC TRANSPORT
  {
    id: 'transport_ridership',
    name: 'Daily Ridership',
    nameFr: 'Fréquentation journalière',
    category: 'public_transport',
    calculation: 'Total passengers per day',
    unit: 'passengers/day',
    format: 'number',
    target: 100000,
    sdgAlignment: 'ODD 11.2',
    frequency: 'daily',
    dimensions: ['mode', 'line', 'station'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_service_frequency',
    name: 'Service Frequency',
    nameFr: 'Fréquence de service',
    category: 'public_transport',
    calculation: 'Average minutes between vehicles',
    unit: 'minutes',
    format: 'number',
    target: 10,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['mode', 'line', 'period'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_on_time_performance',
    name: 'On-Time Performance',
    nameFr: 'Ponctualité',
    category: 'public_transport',
    calculation: '(On-time trips / Total trips) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 11.2',
    frequency: 'daily',
    dimensions: ['mode', 'line', 'period'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'transport_capacity_utilization',
    name: 'Capacity Utilization',
    nameFr: 'Taux d\'occupation',
    category: 'public_transport',
    calculation: '(Passengers / Seating capacity) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'daily',
    dimensions: ['mode', 'line', 'period'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_fare_revenue',
    name: 'Fare Revenue per Passenger',
    nameFr: 'Recette par passager',
    category: 'public_transport',
    calculation: 'Total fare revenue / Total passengers',
    unit: 'USD',
    format: 'currency',
    target: 0.5,
    frequency: 'monthly',
    dimensions: ['mode', 'fare_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_farebox_recovery',
    name: 'Farebox Recovery Ratio',
    nameFr: 'Ratio de recouvrement tarifaire',
    category: 'public_transport',
    calculation: '(Fare revenue / Operating costs) × 100',
    unit: '%',
    format: 'percentage',
    target: 50,
    frequency: 'monthly',
    dimensions: ['mode'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_transfer_rate',
    name: 'Transfer Rate',
    nameFr: 'Taux de correspondance',
    category: 'public_transport',
    calculation: '(Transfers / Total trips) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    frequency: 'monthly',
    dimensions: ['mode', 'station'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_accessibility',
    name: 'Accessibility Compliance',
    nameFr: 'Conformité accessibilité',
    category: 'public_transport',
    calculation: '(Accessible stops / Total stops) × 100',
    unit: '%',
    format: 'percentage',
    target: 100,
    sdgAlignment: 'ODD 11.2',
    frequency: 'annual',
    dimensions: ['mode', 'type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // TAXI & RIDE-HAILING
  {
    id: 'transport_taxi_availability',
    name: 'Taxi Availability Rate',
    nameFr: 'Disponibilité des taxis',
    category: 'taxi',
    calculation: '(Available taxis / Total registered taxis) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'daily',
    dimensions: ['zone', 'period'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_taxi_response_time',
    name: 'Average Response Time',
    nameFr: 'Temps de réponse moyen',
    category: 'taxi',
    calculation: 'Average time from request to pickup',
    unit: 'minutes',
    format: 'number',
    target: 8,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['zone', 'period'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_trip_completion',
    name: 'Trip Completion Rate',
    nameFr: 'Taux d\'achèvement des courses',
    category: 'taxi',
    calculation: '(Completed trips / Requested trips) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'daily',
    dimensions: ['zone', 'driver_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // FLEET MANAGEMENT
  {
    id: 'transport_fleet_availability',
    name: 'Fleet Availability Rate',
    nameFr: 'Disponibilité de la flotte',
    category: 'fleet',
    calculation: '(Operational vehicles / Total vehicles) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    frequency: 'daily',
    dimensions: ['vehicle_type', 'depot'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'transport_maintenance_ratio',
    name: 'Preventive Maintenance Ratio',
    nameFr: 'Ratio maintenance préventive',
    category: 'fleet',
    calculation: '(Preventive maintenance / Total maintenance) × 100',
    unit: '%',
    format: 'percentage',
    target: 70,
    frequency: 'monthly',
    dimensions: ['vehicle_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_breakdown_rate',
    name: 'Vehicle Breakdown Rate',
    nameFr: 'Taux de panne',
    category: 'fleet',
    calculation: '(Breakdown incidents / Vehicle-km) × 100,000',
    unit: '/100,000 km',
    format: 'number',
    target: 2,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['vehicle_type', 'age'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_average_age',
    name: 'Average Fleet Age',
    nameFr: 'Âge moyen de la flotte',
    category: 'fleet',
    calculation: 'Average age of vehicles in years',
    unit: 'years',
    format: 'number',
    target: 8,
    frequency: 'annual',
    dimensions: ['vehicle_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_utilization_rate',
    name: 'Vehicle Utilization Rate',
    nameFr: 'Taux d\'utilisation véhicules',
    category: 'fleet',
    calculation: '(Distance traveled / Potential distance) × 100',
    unit: '%',
    format: 'percentage',
    target: 75,
    frequency: 'monthly',
    dimensions: ['vehicle_type', 'depot'],
    visualization: { defaultType: 'gauge' }
  },

  // ROAD SAFETY
  {
    id: 'transport_accidents_rate',
    name: 'Traffic Accident Rate',
    nameFr: 'Taux d\'accidents',
    category: 'safety',
    calculation: '(Accidents / Vehicle-km) × 1,000,000',
    unit: '/M km',
    format: 'number',
    target: 5,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 3.6',
    frequency: 'monthly',
    dimensions: ['road_type', 'vehicle_type', 'severity'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_fatalities_rate',
    name: 'Road Fatality Rate',
    nameFr: 'Taux de mortalité routière',
    category: 'safety',
    calculation: '(Fatalities / Population) × 100,000',
    unit: '/100,000',
    format: 'number',
    target: 10,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 3.6',
    frequency: 'annual',
    dimensions: ['region', 'road_user'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_speeding_violations',
    name: 'Speeding Violation Rate',
    nameFr: 'Taux d\'infractions vitesse',
    category: 'safety',
    calculation: '(Speeding violations / Vehicles checked) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    lowerIsBetter: true,
    frequency: 'monthly',
    dimensions: ['road_type', 'vehicle_type'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'transport_seatbelt_use',
    name: 'Seatbelt Usage Rate',
    nameFr: 'Taux de port de ceinture',
    category: 'safety',
    calculation: '(Occupants wearing seatbelt / Total occupants) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 3.6',
    frequency: 'quarterly',
    dimensions: ['road_type', 'vehicle_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },
  {
    id: 'transport_helmet_use',
    name: 'Helmet Usage Rate',
    nameFr: 'Taux de port du casque',
    category: 'safety',
    calculation: '(Motorcyclists with helmet / Total motorcyclists) × 100',
    unit: '%',
    format: 'percentage',
    target: 95,
    sdgAlignment: 'ODD 3.6',
    frequency: 'quarterly',
    dimensions: ['region', 'road_type'],
    visualization: { defaultType: 'gauge', colors: ['#ef4444', '#f59e0b', '#22c55e'] }
  },

  // TRAFFIC MANAGEMENT
  {
    id: 'transport_congestion_index',
    name: 'Congestion Index',
    nameFr: 'Indice de congestion',
    category: 'traffic',
    calculation: '(Travel time / Free-flow time - 1) × 100',
    unit: '%',
    format: 'percentage',
    target: 30,
    lowerIsBetter: true,
    sdgAlignment: 'ODD 11.2',
    frequency: 'daily',
    dimensions: ['road', 'period', 'direction'],
    visualization: { defaultType: 'gauge', colors: ['#22c55e', '#f59e0b', '#ef4444'] }
  },
  {
    id: 'transport_average_speed',
    name: 'Average Traffic Speed',
    nameFr: 'Vitesse moyenne',
    category: 'traffic',
    calculation: 'Average speed on monitored roads',
    unit: 'km/h',
    format: 'number',
    target: 30,
    frequency: 'daily',
    dimensions: ['road', 'period'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_travel_time_reliability',
    name: 'Travel Time Reliability',
    nameFr: 'Fiabilité des temps de parcours',
    category: 'traffic',
    calculation: 'Percentage of trips within expected time',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'weekly',
    dimensions: ['corridor'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_queue_length',
    name: 'Average Queue Length',
    nameFr: 'Longueur moyenne de file',
    category: 'traffic',
    calculation: 'Average queue length at intersections',
    unit: 'meters',
    format: 'number',
    target: 50,
    lowerIsBetter: true,
    frequency: 'daily',
    dimensions: ['intersection', 'period'],
    visualization: { defaultType: 'kpi' }
  },

  // PARKING
  {
    id: 'transport_parking_occupancy',
    name: 'Parking Occupancy Rate',
    nameFr: 'Taux d\'occupation parking',
    category: 'parking',
    calculation: '(Occupied spaces / Total spaces) × 100',
    unit: '%',
    format: 'percentage',
    target: 85,
    frequency: 'hourly',
    dimensions: ['zone', 'facility_type'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_parking_turnover',
    name: 'Parking Turnover Rate',
    nameFr: 'Rotation parking',
    category: 'parking',
    calculation: 'Average vehicles per space per day',
    unit: 'vehicles/space',
    format: 'number',
    target: 4,
    frequency: 'daily',
    dimensions: ['zone'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_parking_revenue',
    name: 'Parking Revenue per Space',
    nameFr: 'Recette parking par place',
    category: 'parking',
    calculation: 'Total revenue / Number of spaces',
    unit: 'USD/space',
    format: 'currency',
    target: 100,
    frequency: 'monthly',
    dimensions: ['zone', 'facility_type'],
    visualization: { defaultType: 'kpi' }
  },

  // ACTIVE TRANSPORT
  {
    id: 'transport_cycling_network',
    name: 'Cycling Network Coverage',
    nameFr: 'Couverture réseau cyclable',
    category: 'active_transport',
    calculation: 'Total km of cycling paths',
    unit: 'km',
    format: 'number',
    target: 200,
    sdgAlignment: 'ODD 11.2',
    frequency: 'annual',
    dimensions: ['type', 'region'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_cycling_share',
    name: 'Cycling Modal Share',
    nameFr: 'Part modale vélo',
    category: 'active_transport',
    calculation: '(Cycling trips / Total trips) × 100',
    unit: '%',
    format: 'percentage',
    target: 10,
    sdgAlignment: 'ODD 11.2',
    frequency: 'annual',
    dimensions: ['region', 'purpose'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_walking_share',
    name: 'Walking Modal Share',
    nameFr: 'Part modale marche',
    category: 'active_transport',
    calculation: '(Walking trips / Total trips) × 100',
    unit: '%',
    format: 'percentage',
    target: 25,
    sdgAlignment: 'ODD 11.2',
    frequency: 'annual',
    dimensions: ['region', 'purpose'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_sidewalk_coverage',
    name: 'Sidewalk Coverage',
    nameFr: 'Couverture trottoirs',
    category: 'active_transport',
    calculation: '(Roads with sidewalks / Total roads) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    sdgAlignment: 'ODD 11.2',
    frequency: 'annual',
    dimensions: ['region'],
    visualization: { defaultType: 'gauge' }
  },

  // INTERMODAL
  {
    id: 'transport_intermodal_hub',
    name: 'Intermodal Hub Usage',
    nameFr: 'Utilisation hubs intermodaux',
    category: 'intermodal',
    calculation: 'Passengers using intermodal connections per day',
    unit: 'passengers/day',
    format: 'number',
    target: 10000,
    frequency: 'daily',
    dimensions: ['hub', 'connection_type'],
    visualization: { defaultType: 'kpi' }
  },
  {
    id: 'transport_park_ride',
    name: 'Park & Ride Usage',
    nameFr: 'Utilisation parkings relais',
    category: 'intermodal',
    calculation: '(P&R spaces used / Total P&R spaces) × 100',
    unit: '%',
    format: 'percentage',
    target: 80,
    frequency: 'daily',
    dimensions: ['station'],
    visualization: { defaultType: 'gauge' }
  },
  {
    id: 'transport_bike_sharing',
    name: 'Bike-Sharing Trips',
    nameFr: 'Trips vélos partagés',
    category: 'intermodal',
    calculation: 'Total bike-sharing trips per day',
    unit: 'trips/day',
    format: 'number',
    target: 5000,
    sdgAlignment: 'ODD 11.2',
    frequency: 'daily',
    dimensions: ['station'],
    visualization: { defaultType: 'kpi' }
  },
];

export default transportKPIs;
